import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { courses, courseModules, lessons, notifications, user, emissions } from "@/db/schema";
import { eq, and, desc, like } from "drizzle-orm";

/**
 * Intelligent Course Auto-Generation System
 * 
 * This endpoint analyzes company data and automatically generates courses
 * when gaps are detected between recommendations and available learning content.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      userId,
      recommendations = [],
      insights = [],
      complianceGaps = [],
      emissionsData = null,
      trigger = 'manual' // 'manual', 'recommendation', 'insight', 'compliance'
    } = body;

    if (!userId) {
      return NextResponse.json({ 
        error: 'userId is required',
        code: 'MISSING_USER_ID' 
      }, { status: 400 });
    }

    // Get user profile for context
    const [userProfile] = await db.select().from(user).where(eq(user.id, userId)).limit(1);
    
    if (!userProfile) {
      return NextResponse.json({ 
        error: 'User not found',
        code: 'USER_NOT_FOUND' 
      }, { status: 404 });
    }

    // Analyze what courses are needed
    const analysisResult = await analyzeCoursesNeeded(
      userProfile,
      recommendations,
      insights,
      complianceGaps,
      emissionsData
    );

    if (!analysisResult.needsCourses) {
      return NextResponse.json({
        success: true,
        message: "Existing courses adequately cover current recommendations",
        analysis: analysisResult,
        coursesGenerated: 0
      });
    }

    // Generate courses for identified gaps
    const generatedCourses = [];
    
    for (const courseSpec of analysisResult.coursesToGenerate) {
      console.log(`Auto-generating course: ${courseSpec.topic}`);
      
      try {
        const generatedCourse = await generateCourseWithMedia(
          courseSpec,
          userProfile,
          userId
        );
        
        if (generatedCourse) {
          generatedCourses.push(generatedCourse);
          
          // Create notification for the user
          await db.insert(notifications).values({
            userId: userId,
            type: 'insight_available',
            title: '🎓 New Learning Content Available',
            message: `A new course "${courseSpec.topic}" has been automatically generated based on your ${trigger} data.`,
            link: `/app/learn/${generatedCourse.courseId}`,
            metadata: JSON.stringify({
              courseId: generatedCourse.courseId,
              title: courseSpec.topic,
              trigger,
              autoGenerated: true
            }),
            isRead: false,
            createdAt: new Date().toISOString()
          });
        }
      } catch (error) {
        console.error(`Failed to generate course for ${courseSpec.topic}:`, error);
      }
    }

    return NextResponse.json({
      success: true,
      message: `Successfully generated ${generatedCourses.length} courses`,
      analysis: analysisResult,
      coursesGenerated: generatedCourses.length,
      courses: generatedCourses
    });

  } catch (error: any) {
    console.error("Auto-generation error:", error);
    return NextResponse.json(
      { error: "Failed to auto-generate courses", details: error.message },
      { status: 500 }
    );
  }
}

async function analyzeCoursesNeeded(
  userProfile: any,
  recommendations: string[],
  insights: string[],
  complianceGaps: string[],
  emissionsData: any
) {
  // Get existing courses for this user's industry
  const existingCourses = await db.select()
    .from(courses)
    .where(
      and(
        eq(courses.isPublished, true),
        eq(courses.industry, userProfile.companyIndustry || '')
      )
    );

  const existingTopics = existingCourses.map(c => 
    c.title.toLowerCase() + ' ' + (c.description || '').toLowerCase()
  ).join(' ');

  // Analyze gaps
  const coursesToGenerate = [];
  
  // 1. Analyze recommendations
  for (const rec of recommendations) {
    const topics = extractTopics(rec);
    for (const topic of topics) {
      if (!existingTopics.includes(topic.toLowerCase())) {
        coursesToGenerate.push({
          topic: `Implementing ${topic}`,
          source: 'recommendation',
          priority: 'high',
          context: rec,
          industry: userProfile.companyIndustry,
          difficultyLevel: 'intermediate'
        });
      }
    }
  }

  // 2. Analyze compliance gaps
  for (const gap of complianceGaps) {
    const topics = extractTopics(gap);
    for (const topic of topics) {
      if (!existingTopics.includes(topic.toLowerCase()) && 
          !coursesToGenerate.some(c => c.topic.includes(topic))) {
        coursesToGenerate.push({
          topic: `Compliance Guide: ${topic}`,
          source: 'compliance',
          priority: 'high',
          context: gap,
          industry: userProfile.companyIndustry,
          difficultyLevel: 'intermediate'
        });
      }
    }
  }

  // 3. Analyze emissions hotspots
  if (emissionsData) {
    const hotspots = identifyEmissionsHotspots(emissionsData);
    for (const hotspot of hotspots) {
      if (!existingTopics.includes(hotspot.toLowerCase()) &&
          !coursesToGenerate.some(c => c.topic.includes(hotspot))) {
        coursesToGenerate.push({
          topic: `Reducing ${hotspot} Emissions`,
          source: 'emissions_data',
          priority: 'medium',
          context: `High emissions detected in ${hotspot}`,
          industry: userProfile.companyIndustry,
          difficultyLevel: 'beginner'
        });
      }
    }
  }

  // Limit to top 3 most important courses
  const prioritizedCourses = coursesToGenerate
    .sort((a, b) => {
      const priorityMap: any = { high: 3, medium: 2, low: 1 };
      return priorityMap[b.priority] - priorityMap[a.priority];
    })
    .slice(0, 3);

  return {
    needsCourses: prioritizedCourses.length > 0,
    existingCourseCount: existingCourses.length,
    gapsIdentified: coursesToGenerate.length,
    coursesToGenerate: prioritizedCourses,
    analysis: {
      recommendations: recommendations.length,
      complianceGaps: complianceGaps.length,
      emissionsHotspots: emissionsData ? identifyEmissionsHotspots(emissionsData).length : 0
    }
  };
}

function extractTopics(text: string): string[] {
  const topics = [];
  
  // Common sustainability keywords
  const keywords = [
    'renewable energy', 'solar', 'wind power', 'carbon footprint',
    'waste management', 'recycling', 'circular economy', 
    'energy efficiency', 'water conservation', 'supply chain',
    'esg reporting', 'compliance', 'emissions reduction',
    'sustainable practices', 'green building', 'transportation'
  ];
  
  const lowerText = text.toLowerCase();
  for (const keyword of keywords) {
    if (lowerText.includes(keyword)) {
      topics.push(keyword);
    }
  }
  
  return [...new Set(topics)]; // Remove duplicates
}

function identifyEmissionsHotspots(emissionsData: any): string[] {
  const hotspots = [];
  
  if (emissionsData.electricity > 40) hotspots.push('Electricity');
  if (emissionsData.gas > 30) hotspots.push('Natural Gas');
  if (emissionsData.transportation > 25) hotspots.push('Transportation');
  if (emissionsData.waste > 20) hotspots.push('Waste');
  
  return hotspots;
}

async function generateCourseWithMedia(
  courseSpec: any,
  userProfile: any,
  userId: string
) {
  const prompt = `You are a sustainability education expert creating professional, comprehensive courses for business professionals.

Topic: ${courseSpec.topic}
Industry: ${courseSpec.industry || 'general'}
Context: ${courseSpec.context}
Difficulty: ${courseSpec.difficultyLevel}
Company: ${userProfile.companyName || 'SME'}

Create a DETAILED, COMPREHENSIVE course with substantial educational value:

CRITICAL REQUIREMENTS:
- Each text lesson MUST contain 800-1500 words of rich, detailed content
- Include multiple sections with H2/H3 headings
- Provide specific industry examples, case studies, and real-world scenarios
- Add actionable steps, best practices, and implementation guidance
- Include statistics, data points, and research findings where relevant
- Use proper HTML formatting with paragraphs, lists, bold/italic emphasis
- Make content practical and immediately applicable for ${courseSpec.industry} businesses

Course Structure:
- 3-4 comprehensive modules
- 4-5 detailed lessons per module
- Mix of content types: text (detailed articles), video (demonstrations), quiz (knowledge checks), exercise (hands-on activities)
- Total estimated time: 4-8 hours of substantial learning

Content Depth Guidelines:
- Text lessons: 800-1500 words, multiple sections, examples, case studies
- Video lessons: Include detailed descriptions and learning objectives
- Quizzes: 4-6 questions with detailed explanations
- Exercises: Multi-step practical activities with clear deliverables

CRITICAL: Return ONLY valid JSON (no markdown, no code blocks):

{
  "title": "Course Title",
  "description": "Comprehensive 3-4 sentence description explaining course value, learning outcomes, and target audience",
  "estimatedHours": 5,
  "modules": [
    {
      "title": "Module Title",
      "description": "Detailed module description (2-3 sentences)",
      "estimatedMinutes": 90,
      "lessons": [
        {
          "title": "Lesson Title",
          "contentType": "text",
          "estimatedMinutes": 25,
          "content": {
            "text": "<h2>Main Section Heading</h2><p>Comprehensive opening paragraph introducing the topic with context and relevance for ${courseSpec.industry} businesses. Include specific examples and data points.</p><h3>Subsection 1: Key Concept</h3><p>Detailed explanation with multiple paragraphs covering the concept thoroughly. Include real-world examples, case studies, and specific applications.</p><ul><li><strong>Point 1:</strong> Detailed explanation with examples</li><li><strong>Point 2:</strong> Detailed explanation with data</li><li><strong>Point 3:</strong> Detailed explanation with best practices</li></ul><h3>Subsection 2: Implementation</h3><p>Step-by-step guidance with specific actions. Multiple paragraphs covering different aspects.</p><h3>Subsection 3: Common Challenges</h3><p>Detailed discussion of challenges and solutions.</p><p>Concluding paragraph with key takeaways and next steps.</p>"
          },
          "needsImage": true,
          "imagePrompt": "Professional sustainability concept image"
        },
        {
          "title": "Video Lesson",
          "contentType": "video",
          "estimatedMinutes": 10,
          "content": {
            "text": "<p>Detailed video lesson description with learning objectives</p>"
          },
          "needsVideo": true,
          "videoPrompt": "8-second sustainability demonstration"
        }
      ]
    }
  ]
}`;

  try {
    const response = await fetch(`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/gemini/analyze`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt })
    });

    const result = await response.json();
    let cleanedText = result.text.trim();
    
    // Remove markdown code blocks
    if (cleanedText.startsWith('```json')) {
      cleanedText = cleanedText.replace(/^```json\n/, '').replace(/\n```$/, '');
    } else if (cleanedText.startsWith('```')) {
      cleanedText = cleanedText.replace(/^```\n/, '').replace(/\n```$/, '');
    }
    
    const courseStructure = JSON.parse(cleanedText);

    // Generate course thumbnail image
    let thumbnailUrl = null;
    try {
      console.log(`Generating thumbnail for course: ${courseStructure.title}`);
      const thumbnailResponse = await fetch(`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/generate-image`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: `Professional sustainability course thumbnail for "${courseStructure.title}", modern educational design, clean corporate style, featuring green environmental themes, ${courseSpec.industry} industry context, high quality digital illustration`,
          aspect_ratio: "16:9"
        })
      });

      if (thumbnailResponse.ok) {
        const thumbnailData = await thumbnailResponse.text();
        if (thumbnailData && !thumbnailData.startsWith('Error:')) {
          thumbnailUrl = thumbnailData.trim().split('\n')[0];
          console.log(`✓ Thumbnail generated successfully`);
        }
      }
    } catch (error) {
      console.error(`Failed to generate course thumbnail:`, error);
    }

    // Create course in database
    const [newCourse] = await db.insert(courses).values({
      title: courseStructure.title,
      description: courseStructure.description,
      industry: courseSpec.industry || '',
      difficultyLevel: courseSpec.difficultyLevel,
      estimatedHours: courseStructure.estimatedHours || 4,
      isPublished: true,
      thumbnailUrl: thumbnailUrl,
      createdBy: userId,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }).returning();

    const courseId = newCourse.id;

    // Generate modules and lessons with media
    for (const [moduleIndex, module] of courseStructure.modules.entries()) {
      const [newModule] = await db.insert(courseModules).values({
        courseId,
        order: moduleIndex + 1,
        title: module.title,
        description: module.description,
        estimatedMinutes: module.estimatedMinutes,
        createdAt: new Date().toISOString()
      }).returning();

      const moduleId = newModule.id;

      for (const [lessonIndex, lesson] of module.lessons.entries()) {
        // Generate media if needed
        let videoUrl = null;
        let enhancedContent = { ...lesson.content };

        if (lesson.needsVideo && lesson.videoPrompt) {
          try {
            console.log(`Generating video for lesson: ${lesson.title}`);
            const videoResponse = await fetch(`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/generate-video`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                prompt: lesson.videoPrompt,
                aspect_ratio: "16:9"
              })
            });

            if (videoResponse.ok) {
              const videoData = await videoResponse.text();
              if (videoData && !videoData.startsWith('Error:')) {
                videoUrl = videoData.trim();
                enhancedContent.videoUrl = videoUrl;
              }
            }
          } catch (error) {
            console.error(`Failed to generate video for ${lesson.title}:`, error);
          }
        }

        if (lesson.needsImage && lesson.imagePrompt) {
          try {
            console.log(`Generating image for lesson: ${lesson.title}`);
            const imageResponse = await fetch(`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/generate-image`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                prompt: lesson.imagePrompt,
                aspect_ratio: "16:9"
              })
            });

            if (imageResponse.ok) {
              const imageData = await imageResponse.text();
              if (imageData && !imageData.startsWith('Error:')) {
                const imageUrl = imageData.trim().split('\n')[0];
                enhancedContent.imageUrl = imageUrl;
                // Add image to HTML content
                if (enhancedContent.text) {
                  enhancedContent.text = `<img src="${imageUrl}" alt="${lesson.title}" style="width:100%;max-width:800px;height:auto;border-radius:8px;margin-bottom:1rem;" />${enhancedContent.text}`;
                }
              }
            }
          } catch (error) {
            console.error(`Failed to generate image for ${lesson.title}:`, error);
          }
        }

        await db.insert(lessons).values({
          moduleId,
          order: lessonIndex + 1,
          title: lesson.title,
          contentType: lesson.contentType,
          contentJson: JSON.stringify(enhancedContent),
          videoUrl: videoUrl,
          estimatedMinutes: lesson.estimatedMinutes,
          createdAt: new Date().toISOString()
        });
      }
    }

    return {
      courseId,
      title: courseStructure.title,
      description: courseStructure.description
    };

  } catch (error) {
    console.error("Failed to generate course with media:", error);
    throw error;
  }
}