/**
 * Country data for programmatic /tools/ghg-calculator/[country] pages.
 *
 * Each entry powers a country-scoped landing page with a pre-selected grid
 * factor, a domestic worked example, and country-specific FAQs. Grid factors
 * are 2023 EEA / national inventory data (kg CO2e / kWh, location-based).
 *
 * Anti-thin-content guardrail (per Phase 5 plan): every country ships ≥ 300
 * words of unique bilingual copy. Countries without a real domestic source
 * or unique story stay off this list — no autogenerated filler.
 */

export type CountrySlug =
  | "cyprus"
  | "greece"
  | "germany"
  | "france"
  | "spain"
  | "italy"
  | "netherlands"
  | "poland";

/** Matches the Region keys of GhgCalculator's GRID_FACTORS. */
export type CountryRegion = "CY" | "GR" | "DE" | "FR" | "ES" | "IT" | "NL" | "PL";

export type CountryFaq = { q: string; a: string };

export type CountryLocaleContent = {
  /** Country name in this locale, e.g. "Cyprus" / "Κύπρος". */
  name: string;
  /** Hero eyebrow, e.g. "GHG Calculator · Cyprus". */
  eyebrow: string;
  /** H1 — must contain country name naturally. */
  title: string;
  /** Hero subtitle — 1-2 sentences framing the country's grid + reporting context. */
  subtitle: string;
  /** Meta title (<60 chars ideal). */
  metaTitle: string;
  /** Meta description (<160 chars). */
  metaDescription: string;
  /** Card blurb for cross-links between country pages. */
  cardBlurb: string;
  /** One paragraph in the methodology section explaining the domestic source. */
  methodologyNote: string;
  /** Full worked-example paragraph — real SME profile scoped to this country. */
  workedExample: string;
  /** 3 short bullets on the country's top emission drivers / grid mix. */
  drivers: [string, string, string];
  /** 2 country-specific FAQs (in addition to the 3 shared ones injected server-side). */
  faq: [CountryFaq, CountryFaq];
};

export type CountryEntry = {
  slug: CountrySlug;
  region: CountryRegion;
  iso: string;
  /** 2023 location-based grid factor, kg CO2e / kWh. */
  gridFactor: number;
  factorYear: number;
  factorSource: string;
  factorSourceUrl?: string;
  en: CountryLocaleContent;
  el: CountryLocaleContent;
};

/* ============================== */
/* Country entries                */
/* ============================== */

export const COUNTRIES: CountryEntry[] = [
  /* ---------- Cyprus ---------- */
  {
    slug: "cyprus",
    region: "CY",
    iso: "CY",
    gridFactor: 0.622,
    factorYear: 2023,
    factorSource: "EEA / Cyprus National Inventory Report 2024",
    factorSourceUrl: "https://www.eea.europa.eu/en/analysis/indicators/greenhouse-gas-emission-intensity-of-1",
    en: {
      name: "Cyprus",
      eyebrow: "GHG Calculator · Cyprus",
      title: "GHG emissions calculator for Cyprus — 2024 grid factor 0.622 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the Cyprus grid factor pre-loaded. Free, no signup, built for Cypriot SMEs preparing for VSME, CSRD or bank-driven ESG questionnaires.",
      metaTitle: "GHG Calculator — Cyprus | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with Cyprus's 0.622 kg/kWh grid factor pre-loaded. Scope 1, 2 and 3, PDF export, no signup. For Cypriot SMEs and CFOs.",
      cardBlurb: "Cyprus grid 0.622 kg/kWh — fuel-oil heavy, still Europe's most carbon-intensive grid.",
      methodologyNote:
        "Cyprus's 2023 electricity emission factor of 0.622 kg CO₂e/kWh is drawn from the EEA and the country's National Inventory Report 2024. The Vasilikos and Dhekelia power stations still burn heavy fuel oil and diesel for baseload — that fuel mix is what makes the Cypriot grid the highest-carbon in the EU.",
      workedExample:
        "Take a Nicosia-based consultancy with 45 people and 120,000 kWh of annual grid electricity. On the Cypriot factor of 0.622, Scope 2 alone reaches 74.6 tCO₂e — more than 12× what the same building would emit if it sat in France. Add typical Scope 1 (a small diesel backup generator, 800 L) and Scope 3 (25,000 km of business driving, 15,000 km of intra-EU flights, €400k of purchased services), and the total footprint sits around 220 tCO₂e / year. The lever is unambiguous: a corporate PPA or Guarantee-of-Origin tariff cuts Scope 2 to near zero and shifts the emissions story from grid captive to genuine value-chain work on Scope 3.",
      drivers: [
        "Heavy fuel oil + diesel still supply the bulk of baseload electricity generation.",
        "The EuroAsia Interconnector (scheduled for late-decade) will link Cyprus to Israel and Greece and open the door to grid decarbonisation.",
        "Rooftop solar is scaling fast but curtailment and storage limits keep grid displacement below its technical potential.",
      ],
      faq: [
        {
          q: "Why is Cyprus's grid emission factor so high compared to the EU average?",
          a: "Cyprus is an electricity island with no cross-border interconnector yet in operation. Baseload comes from heavy fuel oil and diesel at Vasilikos and Dhekelia — fuels that emit roughly 3× more CO₂ per kWh than a modern combined-cycle gas plant. The EU-27 average sits near 0.253 kg CO₂e/kWh; Cyprus is 2.5× that.",
        },
        {
          q: "Does the calculator support Cypriot Guarantees of Origin or PPAs?",
          a: "The calculator uses the location-based method — the physical grid factor for Cyprus (0.622). If you hold Guarantees of Origin or have signed a PPA, calculate the market-based number separately using your supplier's residual mix. The GHG Protocol requires both figures to be disclosed for Scope 2.",
        },
      ],
    },
    el: {
      name: "Κύπρος",
      eyebrow: "Υπολογιστής GHG · Κύπρος",
      title: "Υπολογιστής εκπομπών GHG για την Κύπρο — συντελεστής δικτύου 2024: 0,622 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε τις εκπομπές Scope 1, 2 και 3 του οργανισμού σας με προεπιλεγμένο τον κυπριακό συντελεστή δικτύου. Δωρεάν, χωρίς εγγραφή, για κυπριακές ΜμΕ που προετοιμάζονται για VSME, CSRD ή τραπεζικά ερωτηματολόγια ESG.",
      metaTitle: "Υπολογιστής GHG — Κύπρος | Δωρεάν εργαλείο Scope 1, 2 & 3 | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο τον κυπριακό συντελεστή 0,622 kg/kWh. Scope 1, 2 και 3, εξαγωγή PDF, χωρίς εγγραφή.",
      cardBlurb: "Κυπριακό δίκτυο 0,622 kg/kWh — υψηλότερος συντελεστής στην ΕΕ, κυριαρχία μαζούτ.",
      methodologyNote:
        "Ο συντελεστής εκπομπών ηλεκτρισμού της Κύπρου για το 2023 (0,622 kg CO₂e/kWh) προέρχεται από τον ΕΟΠ και την Εθνική Έκθεση Απογραφής 2024. Οι σταθμοί Βασιλικού και Δεκέλειας εξακολουθούν να καίνε μαζούτ και ντίζελ για φορτίο βάσης — αυτή η ενεργειακή σύνθεση εξηγεί γιατί το κυπριακό δίκτυο είναι το πιο ρυπογόνο της ΕΕ.",
      workedExample:
        "Ας θεωρήσουμε μια συμβουλευτική εταιρεία στη Λευκωσία με 45 εργαζόμενους και 120.000 kWh ετήσιου ηλεκτρισμού. Με τον κυπριακό συντελεστή 0,622, το Scope 2 φτάνει μόνο του τους 74,6 tCO₂e — πάνω από 12× αυτό που θα εξέπεμπε το ίδιο κτίριο στη Γαλλία. Προσθέστε τυπικό Scope 1 (μικρή γεννήτρια ντίζελ 800 L) και Scope 3 (25.000 km επαγγελματικών ταξιδιών, 15.000 km ενδοευρωπαϊκών πτήσεων, €400χιλ αγορές υπηρεσιών), και το συνολικό αποτύπωμα φτάνει τους ~220 tCO₂e / έτος. Ο μοχλός είναι σαφής: ένα εταιρικό PPA ή τιμολόγιο με Εγγυήσεις Προέλευσης μηδενίζει σχεδόν το Scope 2 και μετατοπίζει τη συζήτηση στην αλυσίδα αξίας (Scope 3).",
      drivers: [
        "Μαζούτ και ντίζελ εξακολουθούν να καλύπτουν το μεγαλύτερο μέρος του φορτίου βάσης.",
        "Ο διασυνδετήρας EuroAsia (αναμένεται στα τέλη της δεκαετίας) θα συνδέσει την Κύπρο με Ισραήλ και Ελλάδα, ανοίγοντας τον δρόμο για απανθρακοποίηση.",
        "Τα φωτοβολταϊκά στέγης επεκτείνονται γρήγορα, αλλά περιορισμοί curtailment και αποθήκευσης συγκρατούν την πραγματική μετατόπιση.",
      ],
      faq: [
        {
          q: "Γιατί είναι τόσο υψηλός ο συντελεστής του κυπριακού δικτύου συγκριτικά με τον ευρωπαϊκό μέσο;",
          a: "Η Κύπρος είναι ηλεκτρικό νησί χωρίς διασυνδέσεις σε λειτουργία. Το φορτίο βάσης προέρχεται από μαζούτ και ντίζελ στον Βασιλικό και τη Δεκέλεια — καύσιμα με ~3× υψηλότερες εκπομπές ανά kWh από σύγχρονο σταθμό συνδυασμένου κύκλου. Ο μέσος όρος ΕΕ-27 είναι 0,253 kg CO₂e/kWh· η Κύπρος 2,5× αυτόν.",
        },
        {
          q: "Υποστηρίζει το εργαλείο κυπριακές Εγγυήσεις Προέλευσης ή PPA;",
          a: "Ο υπολογιστής χρησιμοποιεί τη μέθοδο βάσει τοποθεσίας — τον φυσικό συντελεστή δικτύου (0,622). Εάν έχετε Εγγυήσεις Προέλευσης ή έχετε υπογράψει PPA, υπολογίστε το market-based ξεχωριστά με το residual mix του προμηθευτή. Το GHG Protocol απαιτεί και τα δύο.",
        },
      ],
    },
  },

  /* ---------- Greece ---------- */
  {
    slug: "greece",
    region: "GR",
    iso: "GR",
    gridFactor: 0.371,
    factorYear: 2023,
    factorSource: "EEA / Greek National Inventory Report 2024",
    en: {
      name: "Greece",
      eyebrow: "GHG Calculator · Greece",
      title: "GHG emissions calculator for Greece — 2024 grid factor 0.371 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the Greek grid factor pre-loaded. Free, no signup, built for Greek businesses preparing CSRD or VSME reports.",
      metaTitle: "GHG Calculator — Greece | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with Greece's 0.371 kg/kWh grid factor pre-loaded. Scope 1, 2 and 3, PDF export, no signup.",
      cardBlurb: "Greek grid 0.371 kg/kWh — lignite phase-out under way, solar and wind scaling.",
      methodologyNote:
        "Greece's 2023 electricity factor of 0.371 kg CO₂e/kWh reflects the mid-transition state of the grid: lignite plants like Ptolemaida still contribute, but their share has dropped sharply since 2019. Utility-scale solar and wind capacity have more than doubled in the same window.",
      workedExample:
        "A 30-person software firm in Athens using 85,000 kWh of electricity, minimal on-site fuel, 18,000 km of business driving and €280k of purchased services generates roughly 31.5 tCO₂e Scope 2, 2 tCO₂e Scope 1, and 105 tCO₂e Scope 3 (dominated by spend-based screening). Total: ~138 tCO₂e / year. Switching to a green tariff via HEDNO's Guarantee-of-Origin system takes Scope 2 down to near zero; the Scope 3 spend line is the next material lever and needs supplier-specific data before disclosure.",
      drivers: [
        "Lignite exit is legally scheduled: DEI plans full closure of its coal fleet by 2028.",
        "Solar PV additions in 2023 exceeded 1.5 GW; wind capacity is now above 5 GW.",
        "Interconnector to Cyprus (EuroAsia) and existing links with Italy/Bulgaria give Greece flexibility other Mediterranean countries lack.",
      ],
      faq: [
        {
          q: "Is Greece's grid factor expected to keep falling?",
          a: "Yes. Greece has legislated a 2028 lignite exit and PPA volumes are growing double-digits year-on-year. The National Energy and Climate Plan targets a grid factor around 0.12 kg/kWh by 2030 — meaning today's disclosures should already flag Scope 2 as declining even without operational changes.",
        },
        {
          q: "How do I handle multiple sites across Greek islands?",
          a: "For the mainland grid, use the national factor (0.371). Non-interconnected islands (many in the Aegean) still run on local diesel gensets — their factor is closer to 0.85. If a large share of your consumption is on such an island, model that site separately.",
        },
      ],
    },
    el: {
      name: "Ελλάδα",
      eyebrow: "Υπολογιστής GHG · Ελλάδα",
      title: "Υπολογιστής εκπομπών GHG για την Ελλάδα — συντελεστής δικτύου 2024: 0,371 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε τις εκπομπές Scope 1, 2 και 3 με προεπιλεγμένο τον ελληνικό συντελεστή δικτύου. Δωρεάν, χωρίς εγγραφή, για ελληνικές επιχειρήσεις που ετοιμάζουν αναφορές CSRD ή VSME.",
      metaTitle: "Υπολογιστής GHG — Ελλάδα | Δωρεάν εργαλείο Scope 1, 2 & 3 | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο τον ελληνικό συντελεστή 0,371 kg/kWh. Scope 1, 2 και 3, εξαγωγή PDF, χωρίς εγγραφή.",
      cardBlurb: "Ελληνικό δίκτυο 0,371 kg/kWh — απολιγνιτοποίηση σε εξέλιξη, ήλιος και άνεμος σε άνοδο.",
      methodologyNote:
        "Ο ελληνικός συντελεστής 2023 (0,371 kg CO₂e/kWh) αποτυπώνει το ενδιάμεσο στάδιο της ενεργειακής μετάβασης: οι λιγνιτικές μονάδες (π.χ. Πτολεμαΐδα) εξακολουθούν να συνεισφέρουν, αλλά το μερίδιό τους έχει μειωθεί δραστικά από το 2019. Παράλληλα, ήλιος και άνεμος έχουν υπερδιπλασιαστεί.",
      workedExample:
        "Μια εταιρεία λογισμικού 30 ατόμων στην Αθήνα με 85.000 kWh ηλεκτρισμού, ελάχιστα καύσιμα επιτόπου, 18.000 km επαγγελματικών ταξιδιών και €280χιλ αγορές υπηρεσιών παράγει περίπου 31,5 tCO₂e Scope 2, 2 tCO₂e Scope 1 και 105 tCO₂e Scope 3 (κυρίως spend-based). Σύνολο: ~138 tCO₂e / έτος. Ένα «πράσινο» τιμολόγιο μέσω Εγγυήσεων Προέλευσης του ΔΑΠΕΕΠ μηδενίζει σχεδόν το Scope 2· η γραμμή δαπανών Scope 3 είναι ο επόμενος μοχλός και χρειάζεται δεδομένα προμηθευτή πριν από αποκάλυψη.",
      drivers: [
        "Έξοδος από τον λιγνίτη νομοθετημένη: η ΔΕΗ σχεδιάζει πλήρη παύση έως το 2028.",
        "Το 2023 προστέθηκαν >1,5 GW φωτοβολταϊκών· η αιολική ισχύς ξεπέρασε τα 5 GW.",
        "Οι διασυνδέσεις με Ιταλία/Βουλγαρία και το EuroAsia (προς Κύπρο) δίνουν ευελιξία που δεν έχουν άλλες μεσογειακές χώρες.",
      ],
      faq: [
        {
          q: "Αναμένεται να συνεχίσει να μειώνεται ο ελληνικός συντελεστής;",
          a: "Ναι. Η έξοδος από τον λιγνίτη έως 2028 είναι νομοθετημένη και τα PPA αυξάνονται διψήφια ετησίως. Το ΕΣΕΚ στοχεύει σε συντελεστή ~0,12 kg/kWh έως 2030 — άρα οι σημερινές αποκαλύψεις πρέπει να επισημαίνουν το Scope 2 ως φθίνον ακόμη και χωρίς λειτουργικές αλλαγές.",
        },
        {
          q: "Πώς χειρίζομαι πολλαπλά σημεία σε ελληνικά νησιά;",
          a: "Για το ηπειρωτικό δίκτυο χρησιμοποιήστε τον εθνικό συντελεστή (0,371). Μη διασυνδεδεμένα νησιά τρέχουν σε τοπικές γεννήτριες ντίζελ — ο συντελεστής τους πλησιάζει το 0,85. Αν η κατανάλωσή σας σε τέτοιο νησί είναι σημαντική, μοντελοποιήστε αυτόν τον σταθμό ξεχωριστά.",
        },
      ],
    },
  },

  /* ---------- Germany ---------- */
  {
    slug: "germany",
    region: "DE",
    iso: "DE",
    gridFactor: 0.381,
    factorYear: 2023,
    factorSource: "EEA / Umweltbundesamt (UBA) 2024",
    en: {
      name: "Germany",
      eyebrow: "GHG Calculator · Germany",
      title: "GHG emissions calculator for Germany — 2024 grid factor 0.381 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the German grid factor pre-loaded. Free, no signup, built for the Mittelstand preparing CSRD and CBAM disclosures.",
      metaTitle: "GHG Calculator — Germany | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with Germany's 0.381 kg/kWh grid factor pre-loaded. Scope 1, 2 and 3, PDF export, no signup.",
      cardBlurb: "German grid 0.381 kg/kWh — coal exit accelerating, gas transition, wind at record share.",
      methodologyNote:
        "Germany's 2023 electricity factor of 0.381 kg CO₂e/kWh is published by the Umweltbundesamt (UBA). The number is a weighted average of a fuel mix in flux — lignite and hard coal down sharply after 2022, gas and renewables filling the gap. Expect further decline through 2030 as the coal exit accelerates.",
      workedExample:
        "A German manufacturing SME with 90 people, 1.2 GWh of grid electricity, 25,000 L of diesel for its fleet, 3,000 m³ of natural gas for process heat, and €2.1M in purchased goods generates roughly 457 tCO₂e Scope 2, 63 tCO₂e Scope 1, and 735 tCO₂e Scope 3 (mostly spend-based purchased goods). Total: ~1,255 tCO₂e / year. For a Mittelstand supplier to a CSRD-reporting OEM, the Scope 3 purchased-goods line is what the OEM will ask for first — replace it with supplier-specific factors as soon as possible.",
      drivers: [
        "Coal phase-out target moved forward to 2030 in the western states; 2038 remains the legal backstop.",
        "Renewables (mostly wind + solar) supplied over 55% of gross electricity in 2024.",
        "Gas-fired generation grew after 2022 as nuclear closed — this is why the factor hasn't fallen faster.",
      ],
      faq: [
        {
          q: "Should I use the UBA factor or a supplier-specific one?",
          a: "For location-based Scope 2, use the UBA national factor (0.381). For market-based Scope 2, use your supplier's disclosed product mix. Most German utilities publish both a Standard/Öko/Wasserkraft mix and its emission factor — those are what feed market-based reporting.",
        },
        {
          q: "How does CBAM interact with my German electricity emissions?",
          a: "CBAM covers embedded emissions in imported goods (cement, iron/steel, aluminium, fertilisers, hydrogen, electricity from third countries). Your German-consumed electricity is domestic and sits outside CBAM's scope — it's part of your own Scope 2 disclosure. If you import CBAM-covered goods for your operations, use the CBAM Report Generator alongside.",
        },
      ],
    },
    el: {
      name: "Γερμανία",
      eyebrow: "Υπολογιστής GHG · Γερμανία",
      title: "Υπολογιστής εκπομπών GHG για τη Γερμανία — συντελεστής δικτύου 2024: 0,381 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε εκπομπές Scope 1, 2 και 3 με προεπιλεγμένο τον γερμανικό συντελεστή. Δωρεάν, χωρίς εγγραφή, για γερμανικές επιχειρήσεις που ετοιμάζουν CSRD και CBAM.",
      metaTitle: "Υπολογιστής GHG — Γερμανία | Δωρεάν εργαλείο | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο γερμανικό συντελεστή 0,381 kg/kWh. Scope 1, 2, 3, εξαγωγή PDF.",
      cardBlurb: "Γερμανικό δίκτυο 0,381 kg/kWh — απολιγνιτοποίηση, ρεκόρ αιολικής παραγωγής.",
      methodologyNote:
        "Ο γερμανικός συντελεστής 2023 (0,381 kg CO₂e/kWh) δημοσιεύεται από το UBA. Ο αριθμός είναι σταθμισμένος μέσος όρος ενός δυναμικά μεταβαλλόμενου μείγματος — λιγνίτης και λιθάνθρακας έχουν πέσει έντονα μετά το 2022, αέριο και ΑΠΕ καλύπτουν το κενό.",
      workedExample:
        "Μια γερμανική μεταποιητική ΜμΕ με 90 άτομα, 1,2 GWh ηλεκτρισμού, 25.000 L ντίζελ για τον στόλο, 3.000 m³ φυσικού αερίου για θερμότητα διεργασίας και €2,1εκ αγορές υλικών παράγει ~457 tCO₂e Scope 2, 63 tCO₂e Scope 1, και 735 tCO₂e Scope 3 (κυρίως αγορές). Σύνολο: ~1.255 tCO₂e / έτος. Για προμηθευτή Mittelstand σε OEM που αναφέρει CSRD, η γραμμή Scope 3 αγορών είναι αυτή που θα ζητηθεί πρώτη.",
      drivers: [
        "Έξοδος από τον άνθρακα μεταφέρθηκε στο 2030 στα δυτικά κρατίδια· 2038 παραμένει το νομικό όριο.",
        "Οι ΑΠΕ (κυρίως αιολικά + φωτοβολταϊκά) κάλυψαν >55% της ακαθάριστης παραγωγής το 2024.",
        "Η αεριοπαραγωγή αυξήθηκε μετά το 2022 λόγω πυρηνικής εξόδου — γι' αυτό ο συντελεστής δεν πέφτει ταχύτερα.",
      ],
      faq: [
        {
          q: "Να χρησιμοποιήσω τον συντελεστή UBA ή τον προμηθευτή;",
          a: "Για location-based Scope 2 χρησιμοποιήστε τον εθνικό UBA (0,381). Για market-based χρησιμοποιήστε το δημοσιευμένο μείγμα του προμηθευτή σας (Standard/Öko/Wasserkraft).",
        },
        {
          q: "Πώς αλληλεπιδρά το CBAM με τις γερμανικές εκπομπές ρεύματος μου;",
          a: "Το CBAM καλύπτει ενσωματωμένες εκπομπές σε εισαγόμενα αγαθά (τσιμέντο, χάλυβα, αλουμίνιο, λιπάσματα, υδρογόνο, ρεύμα από τρίτες χώρες). Το γερμανικό εγχώριο ρεύμα είναι εκτός CBAM — μέρος του δικού σας Scope 2.",
        },
      ],
    },
  },

  /* ---------- France ---------- */
  {
    slug: "france",
    region: "FR",
    iso: "FR",
    gridFactor: 0.056,
    factorYear: 2023,
    factorSource: "EEA / ADEME Base Empreinte 2024",
    en: {
      name: "France",
      eyebrow: "GHG Calculator · France",
      title: "GHG emissions calculator for France — 2024 grid factor 0.056 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the French grid factor pre-loaded. Free, no signup, aligned with ADEME Base Empreinte factors.",
      metaTitle: "GHG Calculator — France | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with France's 0.056 kg/kWh grid factor pre-loaded. Aligned with ADEME. Scope 1, 2, 3.",
      cardBlurb: "French grid 0.056 kg/kWh — one of the lowest in the world, nuclear-heavy baseload.",
      methodologyNote:
        "France's 2023 electricity factor of 0.056 kg CO₂e/kWh is drawn from ADEME's Base Empreinte and confirmed by EEA. The nuclear fleet (~70% of generation), hydro (~10%) and growing wind + solar give France one of the lowest electricity carbon intensities in the world — roughly 5× lower than the EU average.",
      workedExample:
        "A Lyon-based logistics firm with 60 employees, 480,000 kWh of grid electricity, 90,000 L of diesel for its truck fleet, and €1.4M of purchased services generates just 27 tCO₂e Scope 2 (the grid is that clean), 226 tCO₂e Scope 1 (fleet dominates), and 490 tCO₂e Scope 3. Total: ~743 tCO₂e / year. Unlike in Cyprus or Poland, Scope 2 is a rounding error — decarbonisation for a French firm is almost entirely about Scope 1 fleet electrification and Scope 3 supplier engagement.",
      drivers: [
        "Nuclear supplies around 70% of electricity — the single biggest reason for the ultra-low grid factor.",
        "Reactor availability drives short-term factor variation: 2022's outages temporarily pushed the factor up.",
        "Offshore wind is scaling and will diversify the mix without materially lowering the already very low factor.",
      ],
      faq: [
        {
          q: "Should I use ADEME's Base Empreinte factors for my Bilan Carbone?",
          a: "Yes. If you file a Bilan GES Réglementaire under Article 75 of the Grenelle II law, ADEME Base Empreinte is the accepted source and the same factors this calculator uses. For CSRD, the ADEME numbers are compatible with the location-based method required by ESRS E1.",
        },
        {
          q: "Why is Scope 2 almost negligible for French firms?",
          a: "French electricity is roughly 5× cleaner than the EU average because nuclear supplies most baseload. For a typical office-based firm in France, Scope 2 will often be under 5% of the total footprint — the levers that matter are heating fuels (Scope 1) and purchased goods and services (Scope 3).",
        },
      ],
    },
    el: {
      name: "Γαλλία",
      eyebrow: "Υπολογιστής GHG · Γαλλία",
      title: "Υπολογιστής εκπομπών GHG για τη Γαλλία — συντελεστής δικτύου 2024: 0,056 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε εκπομπές Scope 1, 2 και 3 με προεπιλεγμένο τον γαλλικό συντελεστή. Δωρεάν, χωρίς εγγραφή, ευθυγραμμισμένο με ADEME Base Empreinte.",
      metaTitle: "Υπολογιστής GHG — Γαλλία | Δωρεάν εργαλείο | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο γαλλικό συντελεστή 0,056 kg/kWh. Scope 1, 2, 3, εξαγωγή PDF.",
      cardBlurb: "Γαλλικό δίκτυο 0,056 kg/kWh — από τα χαμηλότερα παγκοσμίως, κυριαρχία πυρηνικής.",
      methodologyNote:
        "Ο γαλλικός συντελεστής 2023 (0,056 kg CO₂e/kWh) προέρχεται από τη Base Empreinte της ADEME. Ο πυρηνικός στόλος (~70% της παραγωγής), το υδροηλεκτρικό (~10%) και οι αναπτυσσόμενες ΑΠΕ δίνουν στη Γαλλία μία από τις χαμηλότερες εντάσεις άνθρακα στον κόσμο.",
      workedExample:
        "Εταιρεία logistics στη Λυών με 60 άτομα, 480.000 kWh ηλεκτρισμού, 90.000 L ντίζελ για φορτηγά και €1,4εκ αγορές παράγει μόλις 27 tCO₂e Scope 2 (τόσο καθαρό είναι το δίκτυο), 226 tCO₂e Scope 1 (κυριαρχία στόλου) και 490 tCO₂e Scope 3. Σύνολο: ~743 tCO₂e / έτος. Σε αντίθεση με Κύπρο ή Πολωνία, το Scope 2 είναι αμελητέο — η απανθρακοποίηση εστιάζει σχεδόν αποκλειστικά σε ηλεκτροκίνηση στόλου (Scope 1) και προμηθευτές (Scope 3).",
      drivers: [
        "Η πυρηνική ενέργεια καλύπτει ~70% — η βασική αιτία του πολύ χαμηλού συντελεστή.",
        "Η διαθεσιμότητα αντιδραστήρων επηρεάζει τη βραχυπρόθεσμη διακύμανση: το 2022 οι διακοπές λειτουργίας ανέβασαν προσωρινά τον συντελεστή.",
        "Τα υπεράκτια αιολικά αναπτύσσονται και θα διαφοροποιήσουν το μείγμα.",
      ],
      faq: [
        {
          q: "Να χρησιμοποιήσω τους συντελεστές Base Empreinte για το Bilan Carbone;",
          a: "Ναι. Για υποχρεωτικό Bilan GES υπό Άρθρο 75 του Grenelle II, η ADEME Base Empreinte είναι η αποδεκτή πηγή — οι ίδιοι συντελεστές που χρησιμοποιεί το εργαλείο. Για CSRD, οι αριθμοί είναι συμβατοί με τη μέθοδο location-based του ESRS E1.",
        },
        {
          q: "Γιατί το Scope 2 είναι σχεδόν αμελητέο για γαλλικές εταιρείες;",
          a: "Το γαλλικό ρεύμα είναι ~5× πιο καθαρό από τον ευρωπαϊκό μέσο. Για τυπική εταιρεία γραφείου στη Γαλλία, το Scope 2 συχνά είναι <5% του συνόλου — οι μοχλοί είναι καύσιμα θέρμανσης (Scope 1) και αγορές (Scope 3).",
        },
      ],
    },
  },

  /* ---------- Spain ---------- */
  {
    slug: "spain",
    region: "ES",
    iso: "ES",
    gridFactor: 0.174,
    factorYear: 2023,
    factorSource: "EEA / MITECO Inventario Nacional 2024",
    en: {
      name: "Spain",
      eyebrow: "GHG Calculator · Spain",
      title: "GHG emissions calculator for Spain — 2024 grid factor 0.174 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the Spanish grid factor pre-loaded. Free, no signup, aligned with MITECO's national inventory.",
      metaTitle: "GHG Calculator — Spain | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with Spain's 0.174 kg/kWh grid factor pre-loaded. Aligned with MITECO. Scope 1, 2 and 3.",
      cardBlurb: "Spanish grid 0.174 kg/kWh — wind and solar leader, coal exit essentially complete.",
      methodologyNote:
        "Spain's 2023 electricity factor of 0.174 kg CO₂e/kWh reflects a grid transformed over the last decade: wind supplies ~24%, solar PV ~14%, nuclear ~20%, hydro variable. Coal is now under 3% of generation. The factor is one of the lowest among large EU economies.",
      workedExample:
        "A Barcelona-based hotel group with 4 properties, 6.5 GWh of grid electricity, 320,000 kWh of natural gas for hot water, and €4.8M in purchased services and food generates 1,131 tCO₂e Scope 2, 65 tCO₂e Scope 1, and 1,680 tCO₂e Scope 3. Total: ~2,876 tCO₂e / year. For hospitality, the Scope 3.1 food-and-beverage supply chain typically dominates; the fastest path to a defensible carbon disclosure is engaging the largest food suppliers on their own data.",
      drivers: [
        "Wind + solar together supply over 40% of Spanish electricity in a typical year.",
        "Coal is essentially phased out — under 3% of the mix and declining every year.",
        "Nuclear contributes ~20% but is scheduled to close between 2027-2035, requiring accelerated renewable additions to keep the factor low.",
      ],
      faq: [
        {
          q: "Which factor applies to a Spanish company reporting under CSRD?",
          a: "For location-based Scope 2, use the MITECO national factor (0.174). For market-based, use your electricity supplier's disclosed mix — most Spanish utilities publish the mix breakdown alongside their CUPS invoices, and CNMC certifies Guarantees of Origin.",
        },
        {
          q: "Do I need to model the Canary Islands and Balearic Islands separately?",
          a: "Yes if a material share of your load is there. The peninsular grid runs at 0.174 kg/kWh, but the island systems have significantly higher factors due to more gas and oil in the mix. Model those sites with a higher factor or ask REE for the island-specific value.",
        },
      ],
    },
    el: {
      name: "Ισπανία",
      eyebrow: "Υπολογιστής GHG · Ισπανία",
      title: "Υπολογιστής εκπομπών GHG για την Ισπανία — συντελεστής δικτύου 2024: 0,174 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε εκπομπές Scope 1, 2 και 3 με προεπιλεγμένο τον ισπανικό συντελεστή. Δωρεάν, χωρίς εγγραφή.",
      metaTitle: "Υπολογιστής GHG — Ισπανία | Δωρεάν εργαλείο | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο ισπανικό συντελεστή 0,174 kg/kWh. Scope 1, 2, 3.",
      cardBlurb: "Ισπανικό δίκτυο 0,174 kg/kWh — ηγέτης σε αιολικά/φωτοβολταϊκά, έξοδος από τον άνθρακα.",
      methodologyNote:
        "Ο ισπανικός συντελεστής 2023 (0,174 kg CO₂e/kWh) αντικατοπτρίζει ένα δίκτυο σε βαθύ μετασχηματισμό: αιολικά ~24%, φωτοβολταϊκά ~14%, πυρηνικά ~20%. Ο άνθρακας είναι <3%.",
      workedExample:
        "Ξενοδοχειακός όμιλος στη Βαρκελώνη με 4 μονάδες, 6,5 GWh ηλεκτρισμού, 320.000 kWh αερίου και €4,8εκ αγορές παράγει 1.131 tCO₂e Scope 2, 65 tCO₂e Scope 1 και 1.680 tCO₂e Scope 3. Σύνολο ~2.876 tCO₂e / έτος. Για τη φιλοξενία, η αλυσίδα τροφίμων στο Scope 3.1 κυριαρχεί συνήθως.",
      drivers: [
        "Αιολικά + φωτοβολταϊκά καλύπτουν πάνω από 40% του ισπανικού ρεύματος σε τυπικό έτος.",
        "Ο άνθρακας έχει ουσιαστικά αποσυρθεί — <3%.",
        "Η πυρηνική ενέργεια συνεισφέρει ~20% αλλά προγραμματίζεται έξοδος 2027-2035.",
      ],
      faq: [
        {
          q: "Ποιος συντελεστής ισχύει για ισπανική εταιρεία που αναφέρει υπό CSRD;",
          a: "Για location-based Scope 2 χρησιμοποιήστε τον εθνικό MITECO (0,174). Για market-based, το δημοσιευμένο μείγμα του προμηθευτή σας.",
        },
        {
          q: "Χρειάζεται να μοντελοποιήσω Κανάρια/Βαλεαρίδες ξεχωριστά;",
          a: "Ναι αν σημαντικό μέρος του φορτίου σας είναι εκεί. Τα νησιωτικά συστήματα έχουν σημαντικά υψηλότερο συντελεστή λόγω αερίου και πετρελαίου.",
        },
      ],
    },
  },

  /* ---------- Italy ---------- */
  {
    slug: "italy",
    region: "IT",
    iso: "IT",
    gridFactor: 0.257,
    factorYear: 2023,
    factorSource: "EEA / ISPRA Inventario Nazionale 2024",
    en: {
      name: "Italy",
      eyebrow: "GHG Calculator · Italy",
      title: "GHG emissions calculator for Italy — 2024 grid factor 0.257 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the Italian grid factor pre-loaded. Free, no signup, aligned with ISPRA's national inventory.",
      metaTitle: "GHG Calculator — Italy | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with Italy's 0.257 kg/kWh grid factor pre-loaded. Aligned with ISPRA. Scope 1, 2, 3.",
      cardBlurb: "Italian grid 0.257 kg/kWh — gas-dominant, renewables growing, no nuclear domestically.",
      methodologyNote:
        "Italy's 2023 electricity factor of 0.257 kg CO₂e/kWh is drawn from ISPRA's national inventory. Natural gas supplies around 45% of generation, renewables (hydro + solar + wind) around 42%. Italy has no domestic nuclear and imports a share of French and Swiss nuclear electricity.",
      workedExample:
        "A Milan-based fashion SME with 55 employees, 260,000 kWh of grid electricity, 12,000 m³ of natural gas for heating, and €3.6M of purchased goods (textiles, leather) generates 67 tCO₂e Scope 2, 26 tCO₂e Scope 1, and 1,260 tCO₂e Scope 3. Total: ~1,353 tCO₂e / year. In fashion, Scope 3 dominates by an order of magnitude — supplier engagement on primary data for textiles and leather is the only meaningful decarbonisation lever.",
      drivers: [
        "Natural gas remains the single largest source at ~45% of generation.",
        "Solar PV grew fastest post-2020; Italy's south is prime PV territory.",
        "Imports (roughly 15% of consumption) come mainly from France and Switzerland — effectively low-carbon nuclear + hydro.",
      ],
      faq: [
        {
          q: "How does ISPRA's factor compare to what Terna publishes?",
          a: "ISPRA (0.257) covers gross generation including auto-producers, and is used for national inventory reporting under UNFCCC. Terna's figure is the transmission-system operator's view. For CSRD/ESRS reporting, ISPRA's number is the accepted location-based reference.",
        },
        {
          q: "What if I have sites in both northern and southern Italy?",
          a: "Italy runs one integrated grid, so a single national factor (0.257) applies to both. Zonal marginal prices vary, but for GHG accounting purposes there is no north/south split.",
        },
      ],
    },
    el: {
      name: "Ιταλία",
      eyebrow: "Υπολογιστής GHG · Ιταλία",
      title: "Υπολογιστής εκπομπών GHG για την Ιταλία — συντελεστής δικτύου 2024: 0,257 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε εκπομπές Scope 1, 2 και 3 με προεπιλεγμένο τον ιταλικό συντελεστή. Δωρεάν, χωρίς εγγραφή.",
      metaTitle: "Υπολογιστής GHG — Ιταλία | Δωρεάν εργαλείο | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο ιταλικό συντελεστή 0,257 kg/kWh. Scope 1, 2, 3.",
      cardBlurb: "Ιταλικό δίκτυο 0,257 kg/kWh — κυριαρχία αερίου, ανάπτυξη ΑΠΕ, χωρίς πυρηνικά εγχώρια.",
      methodologyNote:
        "Ο ιταλικός συντελεστής 2023 (0,257 kg CO₂e/kWh) προέρχεται από το ISPRA. Το φυσικό αέριο καλύπτει ~45% της παραγωγής, οι ΑΠΕ ~42%. Η Ιταλία δεν έχει εγχώρια πυρηνικά και εισάγει μέρος του γαλλικού και ελβετικού πυρηνικού ρεύματος.",
      workedExample:
        "Ιταλική εταιρεία μόδας στο Μιλάνο με 55 άτομα, 260.000 kWh ηλεκτρισμού, 12.000 m³ αερίου και €3,6εκ αγορές (υφάσματα, δέρματα) παράγει 67 tCO₂e Scope 2, 26 tCO₂e Scope 1, και 1.260 tCO₂e Scope 3. Σύνολο ~1.353 tCO₂e / έτος. Στη μόδα, το Scope 3 κυριαρχεί — η εμπλοκή προμηθευτών για πρωτογενή δεδομένα είναι ο μόνος ουσιαστικός μοχλός.",
      drivers: [
        "Το φυσικό αέριο παραμένει η μεγαλύτερη πηγή στο ~45%.",
        "Τα φωτοβολταϊκά αυξάνονται ταχύτερα μετά το 2020.",
        "Οι εισαγωγές (~15% της κατανάλωσης) προέρχονται κυρίως από Γαλλία και Ελβετία.",
      ],
      faq: [
        {
          q: "Πώς συγκρίνεται ο συντελεστής ISPRA με αυτόν της Terna;",
          a: "Ο ISPRA (0,257) καλύπτει ακαθάριστη παραγωγή και χρησιμοποιείται για εθνική απογραφή UNFCCC. Για CSRD/ESRS, ο αριθμός του ISPRA είναι η αποδεκτή αναφορά.",
        },
        {
          q: "Τι γίνεται αν έχω σημεία σε βόρεια και νότια Ιταλία;",
          a: "Η Ιταλία έχει ενοποιημένο δίκτυο, επομένως ισχύει ένας εθνικός συντελεστής (0,257) και για τις δύο περιοχές.",
        },
      ],
    },
  },

  /* ---------- Netherlands ---------- */
  {
    slug: "netherlands",
    region: "NL",
    iso: "NL",
    gridFactor: 0.328,
    factorYear: 2023,
    factorSource: "EEA / CBS 2024",
    en: {
      name: "Netherlands",
      eyebrow: "GHG Calculator · Netherlands",
      title: "GHG emissions calculator for the Netherlands — 2024 grid factor 0.328 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the Dutch grid factor pre-loaded. Free, no signup, aligned with CBS statistics.",
      metaTitle: "GHG Calculator — Netherlands | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with the Netherlands's 0.328 kg/kWh grid factor pre-loaded. Aligned with CBS. Scope 1, 2, 3.",
      cardBlurb: "Dutch grid 0.328 kg/kWh — gas-dominant historically, offshore wind ramping fast.",
      methodologyNote:
        "The Dutch 2023 electricity factor of 0.328 kg CO₂e/kWh reflects a grid still leaning heavily on natural gas (~35%), coal (declining, ~10%), with wind (rising fast, ~25%) and solar (~15%) filling the gap. CBS publishes the number annually as part of the national energy balance.",
      workedExample:
        "An Amsterdam-based fintech SME with 40 employees, 95,000 kWh of grid electricity, minimal on-site fuel, 8,000 km of car travel and €520k of cloud + professional services generates 31 tCO₂e Scope 2, 1 tCO₂e Scope 1, and 189 tCO₂e Scope 3. Total: ~221 tCO₂e / year. In a services-heavy country like the Netherlands, cloud emissions (a Scope 3.1 subcategory now increasingly disclosed) are worth breaking out separately — providers like AWS eu-west-1 and Azure West Europe both publish region-specific factors.",
      drivers: [
        "Coal generation is falling under legislated phase-out (2030) and the 35% cap on coal-fired hours.",
        "Offshore wind is scaling toward 21 GW by 2031 — set to transform the factor by end of decade.",
        "The Netherlands is a large gas producer historically; domestic Groningen production is now essentially wound down.",
      ],
      faq: [
        {
          q: "Which factor should I use for a data centre in the Netherlands?",
          a: "For location-based Scope 2, use the national factor (0.328). For market-based, most hyperscalers in the Netherlands buy Guarantees of Origin covering their electricity — check the provider's PPA disclosure. Cloud region factors from AWS, Azure, and Google Cloud should be used for downstream Scope 3.1 cloud emissions.",
        },
        {
          q: "Is the Dutch factor expected to drop sharply?",
          a: "Yes, faster than the German factor. The offshore wind pipeline through 2031 is roughly 21 GW gross, which — even accounting for gas peakers — should push the grid factor well under 0.15 kg/kWh by 2030. Disclose today's number but flag the trajectory.",
        },
      ],
    },
    el: {
      name: "Ολλανδία",
      eyebrow: "Υπολογιστής GHG · Ολλανδία",
      title: "Υπολογιστής εκπομπών GHG για την Ολλανδία — συντελεστής δικτύου 2024: 0,328 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε εκπομπές Scope 1, 2 και 3 με προεπιλεγμένο τον ολλανδικό συντελεστή. Δωρεάν, χωρίς εγγραφή.",
      metaTitle: "Υπολογιστής GHG — Ολλανδία | Δωρεάν εργαλείο | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο ολλανδικό συντελεστή 0,328 kg/kWh. Scope 1, 2, 3.",
      cardBlurb: "Ολλανδικό δίκτυο 0,328 kg/kWh — ιστορική κυριαρχία αερίου, ταχεία άνοδος υπεράκτιου αιολικού.",
      methodologyNote:
        "Ο ολλανδικός συντελεστής 2023 (0,328 kg CO₂e/kWh) αποτυπώνει ένα δίκτυο ακόμη βασισμένο στο φυσικό αέριο (~35%), με μειούμενο άνθρακα (~10%), ανερχόμενο αιολικό (~25%) και φωτοβολταϊκά (~15%).",
      workedExample:
        "Fintech ΜμΕ στο Άμστερνταμ με 40 άτομα, 95.000 kWh ηλεκτρισμού, ελάχιστα καύσιμα, 8.000 km αυτοκίνητο και €520χιλ υπηρεσίες παράγει 31 tCO₂e Scope 2, 1 tCO₂e Scope 1, και 189 tCO₂e Scope 3. Σύνολο ~221 tCO₂e / έτος. Οι εκπομπές cloud αξίζει να εξατομικευτούν.",
      drivers: [
        "Η παραγωγή από άνθρακα υποχωρεί υπό νομοθετημένη έξοδο (2030).",
        "Το υπεράκτιο αιολικό στοχεύει τα 21 GW έως το 2031.",
        "Η ιστορική εγχώρια παραγωγή αερίου στο Groningen έχει ουσιαστικά σταματήσει.",
      ],
      faq: [
        {
          q: "Ποιος συντελεστής ισχύει για data centre στην Ολλανδία;",
          a: "Για location-based Scope 2, ο εθνικός (0,328). Για market-based, οι περισσότεροι hyperscalers αγοράζουν Εγγυήσεις Προέλευσης — ελέγξτε την PPA αποκάλυψη του παρόχου.",
        },
        {
          q: "Αναμένεται να μειωθεί απότομα;",
          a: "Ναι, ταχύτερα από τον γερμανικό. Ο pipeline υπεράκτιου αιολικού έως 2031 θα φέρει τον συντελεστή κάτω από 0,15 kg/kWh έως 2030.",
        },
      ],
    },
  },

  /* ---------- Poland ---------- */
  {
    slug: "poland",
    region: "PL",
    iso: "PL",
    gridFactor: 0.657,
    factorYear: 2023,
    factorSource: "EEA / KOBiZE 2024",
    en: {
      name: "Poland",
      eyebrow: "GHG Calculator · Poland",
      title: "GHG emissions calculator for Poland — 2024 grid factor 0.657 kg CO₂e/kWh",
      subtitle:
        "Estimate your organisation's Scope 1, 2 and 3 emissions with the Polish grid factor pre-loaded. Free, no signup, aligned with KOBiZE.",
      metaTitle: "GHG Calculator — Poland | Free Scope 1, 2 & 3 Tool | Vuneli",
      metaDescription:
        "Free GHG Protocol calculator with Poland's 0.657 kg/kWh grid factor pre-loaded. Aligned with KOBiZE. Scope 1, 2, 3.",
      cardBlurb: "Polish grid 0.657 kg/kWh — highest in the EU, hard-coal dominant, transition underway.",
      methodologyNote:
        "Poland's 2023 electricity factor of 0.657 kg CO₂e/kWh is published by KOBiZE and reflects a grid still dominated by hard coal and lignite (together ~60% of generation). It is now the highest factor in the EU — Poland's transition is legally committed but slower than in western Europe.",
      workedExample:
        "A Warsaw-based e-commerce SME with 25 people, 55,000 kWh of grid electricity, minimal on-site fuel, 12,000 km of delivery driving and €320k of purchased services generates 36 tCO₂e Scope 2 (heavy for a services business — that's the coal grid), 2 tCO₂e Scope 1, and 116 tCO₂e Scope 3. Total: ~154 tCO₂e / year. In Poland, Scope 2 disproportionately shapes any office-based footprint — a green tariff via Guarantees of Origin (świadectwo pochodzenia) is the fastest reduction lever.",
      drivers: [
        "Hard coal + lignite still supply ~60% of Polish electricity.",
        "First nuclear plant scheduled to come online around 2033 — will materially lower the factor.",
        "Renewables (mainly wind onshore + rooftop solar) are the fastest-growing segment but from a low base.",
      ],
      faq: [
        {
          q: "Why does a small Polish office produce more Scope 2 than a Cypriot one for the same kWh?",
          a: "Because 0.657 (PL) is higher than 0.622 (CY). Poland is the single highest-carbon grid in the EU today. For the same 100,000 kWh of consumption, a Polish office emits 65.7 tCO₂e vs 62.2 tCO₂e in Cyprus, ~35 in the Netherlands, ~17 in Spain and ~5.6 in France.",
        },
        {
          q: "How do świadectwa pochodzenia fit into market-based Scope 2?",
          a: "Polish Guarantees of Origin (świadectwa pochodzenia z OZE) are the equivalent of EU-wide GOs. If you retire them, you can claim the associated electricity as zero-emission for market-based Scope 2 — but you must disclose both location-based (0.657) and market-based figures under the GHG Protocol Scope 2 Guidance.",
        },
      ],
    },
    el: {
      name: "Πολωνία",
      eyebrow: "Υπολογιστής GHG · Πολωνία",
      title: "Υπολογιστής εκπομπών GHG για την Πολωνία — συντελεστής δικτύου 2024: 0,657 kg CO₂e/kWh",
      subtitle:
        "Εκτιμήστε εκπομπές Scope 1, 2 και 3 με προεπιλεγμένο τον πολωνικό συντελεστή. Δωρεάν, χωρίς εγγραφή.",
      metaTitle: "Υπολογιστής GHG — Πολωνία | Δωρεάν εργαλείο | Vuneli",
      metaDescription:
        "Δωρεάν υπολογιστής GHG Protocol με προεπιλεγμένο πολωνικό συντελεστή 0,657 kg/kWh. Scope 1, 2, 3.",
      cardBlurb: "Πολωνικό δίκτυο 0,657 kg/kWh — υψηλότερο στην ΕΕ, κυριαρχία λιθάνθρακα.",
      methodologyNote:
        "Ο πολωνικός συντελεστής 2023 (0,657 kg CO₂e/kWh) δημοσιεύεται από το KOBiZE και αντικατοπτρίζει ένα δίκτυο ακόμη κυριαρχούμενο από λιθάνθρακα και λιγνίτη (~60% της παραγωγής). Είναι σήμερα ο υψηλότερος συντελεστής στην ΕΕ.",
      workedExample:
        "ΜμΕ e-commerce στη Βαρσοβία με 25 άτομα, 55.000 kWh ηλεκτρισμού, 12.000 km διανομές και €320χιλ υπηρεσίες παράγει 36 tCO₂e Scope 2 (υψηλό για επιχείρηση υπηρεσιών — αυτό είναι το ανθρακικό δίκτυο), 2 tCO₂e Scope 1, και 116 tCO₂e Scope 3. Σύνολο ~154 tCO₂e / έτος. Στην Πολωνία, το Scope 2 διαμορφώνει δυσανάλογα το αποτύπωμα οποιασδήποτε επιχείρησης γραφείου.",
      drivers: [
        "Λιθάνθρακας + λιγνίτης καλύπτουν ~60% της παραγωγής.",
        "Ο πρώτος πυρηνικός σταθμός αναμένεται γύρω στο 2033.",
        "Οι ΑΠΕ (αιολικά + φωτοβολταϊκά στέγης) είναι το ταχύτερα αναπτυσσόμενο τμήμα.",
      ],
      faq: [
        {
          q: "Γιατί πολωνικό γραφείο παράγει περισσότερο Scope 2 από κυπριακό;",
          a: "Επειδή 0,657 (PL) > 0,622 (CY). Για τις ίδιες 100.000 kWh, πολωνικό γραφείο εκπέμπει 65,7 tCO₂e έναντι 62,2 tCO₂e στην Κύπρο.",
        },
        {
          q: "Πώς εντάσσονται τα świadectwa pochodzenia στο market-based Scope 2;",
          a: "Οι πολωνικές Εγγυήσεις Προέλευσης είναι ισοδύναμες των ευρωπαϊκών GOs. Με απόσυρσή τους, μπορείτε να δηλώσετε μηδενικές market-based εκπομπές — αλλά πρέπει να αποκαλύψετε και τα δύο νούμερα.",
        },
      ],
    },
  },
];

export const COUNTRY_SLUGS: CountrySlug[] = COUNTRIES.map((c) => c.slug);

export function getCountry(slug: string): CountryEntry | undefined {
  return COUNTRIES.find((c) => c.slug === slug);
}

/** Neighbouring / contrast countries for internal-link mesh. */
export const COUNTRY_NEIGHBOURS: Record<CountrySlug, CountrySlug[]> = {
  cyprus: ["greece", "italy"],
  greece: ["cyprus", "italy"],
  germany: ["netherlands", "france"],
  france: ["germany", "spain"],
  spain: ["france", "italy"],
  italy: ["france", "greece"],
  netherlands: ["germany", "france"],
  poland: ["germany", "netherlands"],
};
