import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { imageUrl, prompt } = await req.json();

    if (!imageUrl || !prompt) {
      return NextResponse.json(
        { error: "Both imageUrl and prompt are required" },
        { status: 400 }
      );
    }

    if (!process.env.GOOGLE_GEMINI_API_KEY) {
      return NextResponse.json(
        { error: "Gemini API key not configured" },
        { status: 500 }
      );
    }

    const client = new GoogleGenAI({
      apiKey: process.env.GOOGLE_GEMINI_API_KEY,
    });

    // Extract base64 data from data URL
    const base64Data = imageUrl.split(',')[1];
    const mimeType = imageUrl.match(/data:([^;]+);/)?.[1] || "image/png";

    // Use Imagen 4.0 for image generation with logo reference
    const response = await client.models.generateImages({
      model: "imagen-4.0-generate-001",
      prompt: prompt,
      config: {
        aspectRatio: "1:1",
        referenceImages: [
          {
            referenceType: "STYLE",
            referenceImage: {
              imageBytes: base64Data
            }
          }
        ]
      } as any
    });

    // Extract generated image from response
    if (response.generatedImages && response.generatedImages.length > 0) {
      const imageBytes = response.generatedImages[0].image?.imageBytes;
      if (imageBytes) {
        const generatedImage = `data:image/png;base64,${imageBytes}`;
        return NextResponse.json({ 
          generatedImage,
          success: true 
        });
      }
    }

    // If no image was generated, return error
    return NextResponse.json(
      { error: "No image generated by Gemini" },
      { status: 500 }
    );
  } catch (error: any) {
    console.error("Gemini vision API error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate image with logo" },
      { status: 500 }
    );
  }
}