import { db } from '@/db';
import { actions } from '@/db/schema';

async function main() {
    const sampleActions = [
        // ENERGY CATEGORY (7 actions)
        {
            title: 'Switch to LED Lighting',
            description: 'Replace all traditional incandescent and fluorescent bulbs with energy-efficient LED alternatives throughout your facility. LED bulbs consume up to 75% less energy and last 25 times longer, providing immediate cost savings while significantly reducing your carbon footprint.',
            category: 'energy',
            impact: '850 kg CO2e/year',
            difficulty: 'easy',
            points: 150,
            iconName: 'bulb',
            isCustom: false,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Install Solar Panel System',
            description: 'Install a comprehensive rooftop solar photovoltaic system to generate clean, renewable energy for your operations. This significant investment provides long-term energy independence, reduces reliance on fossil fuels, and can eliminate up to 80% of your electricity costs over the system\'s 25-year lifespan.',
            category: 'energy',
            impact: '4500 kg CO2e/year',
            difficulty: 'hard',
            points: 500,
            iconName: 'bolt',
            isCustom: false,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Optimize HVAC Systems',
            description: 'Conduct a comprehensive audit of your heating, ventilation, and air conditioning systems to identify inefficiencies and implement optimization strategies. Regular maintenance, filter replacements, and system upgrades can improve efficiency by 20-40%, dramatically reducing energy consumption and operational costs.',
            category: 'energy',
            impact: '1800 kg CO2e/year',
            difficulty: 'medium',
            points: 300,
            iconName: 'fire',
            isCustom: false,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Install Smart Thermostats',
            description: 'Deploy programmable smart thermostats throughout your facility to automatically adjust heating and cooling based on occupancy patterns and time of day. These intelligent devices learn your usage patterns and can reduce energy consumption by up to 23% through optimized temperature control.',
            category: 'energy',
            impact: '600 kg CO2e/year',
            difficulty: 'easy',
            points: 120,
            iconName: 'fire',
            isCustom: false,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'Conduct Energy Audit',
            description: 'Hire a certified energy auditor to perform a detailed assessment of your facility\'s energy consumption patterns and identify specific opportunities for improvement. Professional audits provide actionable recommendations, prioritized by ROI, and often uncover hidden inefficiencies that can lead to 15-30% energy savings.',
            category: 'energy',
            impact: '2100 kg CO2e/year',
            difficulty: 'medium',
            points: 350,
            iconName: 'bolt',
            isCustom: false,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Switch to Renewable Energy',
            description: 'Transition your electricity supply to 100% renewable sources by purchasing green energy directly from your utility provider or through renewable energy certificates. This immediate action eliminates your electricity-related carbon emissions without requiring infrastructure changes or upfront capital investment.',
            category: 'energy',
            impact: '3200 kg CO2e/year',
            difficulty: 'medium',
            points: 400,
            iconName: 'bolt',
            isCustom: false,
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'Install Energy Monitoring System',
            description: 'Implement a real-time energy monitoring system that tracks electricity consumption across your facility with granular detail. These systems provide instant visibility into energy usage patterns, enable quick identification of anomalies, and typically reduce consumption by 10-15% through increased awareness and behavioral changes.',
            category: 'energy',
            impact: '450 kg CO2e/year',
            difficulty: 'easy',
            points: 90,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-02-04').toISOString(),
        },
        // WASTE CATEGORY (7 actions)
        {
            title: 'Implement Recycling Program',
            description: 'Establish a comprehensive multi-stream recycling system with clearly labeled bins for paper, plastics, glass, and metals throughout your facility. Employee education and convenient placement can divert 50-70% of waste from landfills while reducing disposal costs and environmental impact.',
            category: 'waste',
            impact: '400 kg CO2e/year',
            difficulty: 'easy',
            points: 80,
            iconName: 'recycle',
            isCustom: false,
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            title: 'Launch Composting Program',
            description: 'Divert organic waste from landfills by implementing a composting program for food scraps, coffee grounds, and biodegradable materials. Composting prevents methane emissions from landfills and creates nutrient-rich soil amendments, closing the loop on organic waste while reducing disposal costs by up to 30%.',
            category: 'waste',
            impact: '1200 kg CO2e/year',
            difficulty: 'medium',
            points: 220,
            iconName: 'leaf',
            isCustom: false,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'Eliminate Single-Use Plastics',
            description: 'Ban all disposable plastic items in your workplace, including water bottles, utensils, straws, and packaging materials. Provide reusable alternatives and partner with vendors who use sustainable packaging to eliminate plastic waste entirely from your operations.',
            category: 'waste',
            impact: '320 kg CO2e/year',
            difficulty: 'easy',
            points: 65,
            iconName: 'recycle',
            isCustom: false,
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            title: 'Implement Carpool Program',
            description: 'Launch an employee carpooling initiative with preferential parking, financial incentives, and a matching platform to connect commuters with similar routes. Reducing single-occupancy vehicle trips not only cuts emissions but also decreases parking demand and improves employee relationships through shared commutes.',
            category: 'waste',
            impact: '950 kg CO2e/year',
            difficulty: 'medium',
            points: 180,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-01-27').toISOString(),
        },
        {
            title: 'Start Circular Economy Initiative',
            description: 'Transform your business model to emphasize product lifecycle optimization, including design for disassembly, material recovery, and closed-loop supply chains. This comprehensive approach maximizes resource efficiency, minimizes waste generation, and can create new revenue streams through material reclamation and refurbishment programs.',
            category: 'waste',
            impact: '2800 kg CO2e/year',
            difficulty: 'hard',
            points: 450,
            iconName: 'recycle',
            isCustom: false,
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            title: 'E-Waste Recycling Program',
            description: 'Establish a proper electronics disposal and recycling program for computers, phones, and other electronic equipment. Partner with certified e-waste recyclers to ensure hazardous materials are handled safely while recovering valuable metals and components, preventing toxic substances from entering landfills.',
            category: 'waste',
            impact: '280 kg CO2e/year',
            difficulty: 'easy',
            points: 55,
            iconName: 'recycle',
            isCustom: false,
            createdAt: new Date('2024-02-02').toISOString(),
        },
        {
            title: 'Zero-Waste Packaging',
            description: 'Transition all product and shipping packaging to sustainable, biodegradable, or reusable materials. Work with suppliers to eliminate excess packaging, use recycled content, and design packaging that can be easily recycled or composted by end users, dramatically reducing your supply chain\'s environmental footprint.',
            category: 'waste',
            impact: '1400 kg CO2e/year',
            difficulty: 'medium',
            points: 260,
            iconName: 'leaf',
            isCustom: false,
            createdAt: new Date('2024-02-06').toISOString(),
        },
        // WATER CATEGORY (7 actions)
        {
            title: 'Install Low-Flow Fixtures',
            description: 'Replace all standard faucets, showerheads, and toilets with WaterSense-certified low-flow fixtures that reduce water consumption by 20-60% without sacrificing performance. This simple upgrade typically pays for itself within 1-2 years through reduced water and sewage costs.',
            category: 'water',
            impact: '350 kg CO2e/year',
            difficulty: 'easy',
            points: 70,
            iconName: 'water',
            isCustom: false,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            title: 'Install Water Reclamation System',
            description: 'Implement a comprehensive greywater recycling system that captures and treats water from sinks, showers, and washing machines for reuse in toilet flushing, irrigation, and cooling systems. This advanced infrastructure can reduce municipal water consumption by up to 50% while providing resilience against water scarcity.',
            category: 'water',
            impact: '3200 kg CO2e/year',
            difficulty: 'hard',
            points: 450,
            iconName: 'water',
            isCustom: false,
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            title: 'Implement Rainwater Harvesting',
            description: 'Install a rainwater collection system with storage tanks to capture roof runoff for landscape irrigation, cooling tower makeup water, or toilet flushing. This sustainable practice reduces stormwater runoff, decreases municipal water demand, and provides a free, high-quality water source.',
            category: 'water',
            impact: '1100 kg CO2e/year',
            difficulty: 'medium',
            points: 210,
            iconName: 'water',
            isCustom: false,
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            title: 'Install Dual-Flush Toilets',
            description: 'Upgrade all toilet fixtures to dual-flush models that provide a reduced flush option for liquid waste and a full flush for solid waste. This simple technology can reduce toilet water consumption by 67%, making it one of the most cost-effective water conservation measures available.',
            category: 'water',
            impact: '290 kg CO2e/year',
            difficulty: 'easy',
            points: 60,
            iconName: 'water',
            isCustom: false,
            createdAt: new Date('2024-01-26').toISOString(),
        },
        {
            title: 'Water-Efficient Landscaping',
            description: 'Replace traditional lawns with drought-resistant native plants and implement drip irrigation systems that deliver water directly to plant roots. This xeriscaping approach can reduce outdoor water use by 50-75% while creating beautiful, low-maintenance landscapes that support local ecosystems.',
            category: 'water',
            impact: '780 kg CO2e/year',
            difficulty: 'medium',
            points: 150,
            iconName: 'leaf',
            isCustom: false,
            createdAt: new Date('2024-01-29').toISOString(),
        },
        {
            title: 'Install Leak Detection System',
            description: 'Deploy an automated leak detection and monitoring system that uses sensors and smart meters to identify water leaks in real-time. Quick leak detection prevents water waste, property damage, and high utility bills, with typical systems paying for themselves within months through avoided water losses.',
            category: 'water',
            impact: '420 kg CO2e/year',
            difficulty: 'easy',
            points: 85,
            iconName: 'water',
            isCustom: false,
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            title: 'Implement Water Audit',
            description: 'Conduct a professional water audit to analyze consumption patterns, identify inefficiencies, and develop a prioritized action plan for water conservation. Expert auditors use specialized equipment to uncover hidden leaks and wasteful practices, typically identifying opportunities to reduce consumption by 15-40%.',
            category: 'water',
            impact: '950 kg CO2e/year',
            difficulty: 'medium',
            points: 180,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-02-07').toISOString(),
        },
        // OPERATIONS CATEGORY (7 actions)
        {
            title: 'Transition to Paperless Operations',
            description: 'Eliminate paper usage by digitizing all documents, implementing electronic signatures, and adopting cloud-based collaboration tools. This transition reduces filing space requirements, improves document accessibility, and eliminates the environmental impact of paper production, printing, and disposal while enhancing operational efficiency.',
            category: 'operations',
            impact: '250 kg CO2e/year',
            difficulty: 'easy',
            points: 50,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            title: 'Launch Remote Work Policy',
            description: 'Implement a flexible work-from-home program that allows employees to work remotely 2-3 days per week. Remote work eliminates commute emissions, reduces office energy consumption, and improves employee work-life balance while maintaining productivity through modern collaboration technologies.',
            category: 'operations',
            impact: '1600 kg CO2e/year',
            difficulty: 'medium',
            points: 290,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-01-31').toISOString(),
        },
        {
            title: 'Host Sustainability Workshops',
            description: 'Organize quarterly educational workshops that teach employees about sustainable practices, climate science, and practical actions they can take at work and home. Building environmental literacy creates a culture of sustainability, drives behavioral change, and empowers employees to become sustainability champions.',
            category: 'operations',
            impact: '380 kg CO2e/year',
            difficulty: 'easy',
            points: 75,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Create Community Garden',
            description: 'Establish an on-site community garden where employees can grow vegetables, herbs, and flowers using organic methods. Gardens provide fresh, local produce, create green space that reduces urban heat island effects, support pollinators, and build team cohesion through collaborative growing activities.',
            category: 'operations',
            impact: '520 kg CO2e/year',
            difficulty: 'medium',
            points: 110,
            iconName: 'leaf',
            isCustom: false,
            createdAt: new Date('2024-02-08').toISOString(),
        },
        {
            title: 'Organize Beach/Park Cleanups',
            description: 'Host monthly volunteer events where employees participate in local beach or park cleanup activities. These team-building events remove litter from natural areas, prevent plastic pollution from entering waterways, raise environmental awareness, and strengthen your organization\'s connection to the community.',
            category: 'operations',
            impact: '180 kg CO2e/year',
            difficulty: 'easy',
            points: 45,
            iconName: 'leaf',
            isCustom: false,
            createdAt: new Date('2024-02-09').toISOString(),
        },
        {
            title: 'Partner with Environmental NGOs',
            description: 'Establish strategic partnerships with environmental non-profit organizations through financial support, volunteer programs, and collaborative projects. These partnerships amplify your impact beyond your operations, support critical conservation work, and provide opportunities for employee engagement in meaningful environmental initiatives.',
            category: 'operations',
            impact: '850 kg CO2e/year',
            difficulty: 'medium',
            points: 165,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'Implement Green Procurement Policy',
            description: 'Develop comprehensive sustainable purchasing requirements that prioritize suppliers with strong environmental credentials, eco-friendly products, and transparent supply chains. This systematic approach transforms your entire supply chain, drives market demand for sustainable products, and ensures your purchasing decisions align with your environmental values.',
            category: 'operations',
            impact: '2400 kg CO2e/year',
            difficulty: 'hard',
            points: 420,
            iconName: 'target',
            isCustom: false,
            createdAt: new Date('2024-02-11').toISOString(),
        },
    ];

    await db.insert(actions).values(sampleActions);
    
    console.log('✅ Actions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});