import { db } from '@/db';
import { courses, courseModules, lessons } from '@/db/schema';

async function main() {
    const now = new Date().toISOString();

    // Insert Course 1: Carbon Footprint Fundamentals
    const [course1] = await db.insert(courses).values({
        title: 'Carbon Footprint Fundamentals',
        description: 'Learn the essentials of carbon accounting, emission sources, and practical reduction strategies for your business. Perfect for beginners starting their sustainability journey.',
        industry: 'general',
        difficultyLevel: 'beginner',
        estimatedHours: 4.5,
        prerequisites: JSON.stringify([]),
        learningObjectives: JSON.stringify([
            'Understand greenhouse gas emissions and carbon accounting basics',
            'Identify major emission sources in business operations',
            'Calculate your organization\'s carbon footprint',
            'Develop practical reduction strategies'
        ]),
        createdBy: 'ai',
        isPublished: true,
        tags: JSON.stringify(['carbon', 'basics', 'accounting', 'sustainability']),
        thumbnailUrl: '/courses/carbon-fundamentals.jpg',
        createdAt: now,
        updatedAt: now,
    }).returning();

    // Insert modules for Course 1
    const [module1_1] = await db.insert(courseModules).values({
        courseId: course1.id,
        order: 1,
        title: 'Introduction to Carbon Accounting',
        description: 'Understand the fundamentals of carbon accounting and greenhouse gas protocols.',
        estimatedMinutes: 45,
        createdAt: now,
    }).returning();

    const [module1_2] = await db.insert(courseModules).values({
        courseId: course1.id,
        order: 2,
        title: 'Emission Sources',
        description: 'Learn to identify and categorize different types of emissions in your organization.',
        estimatedMinutes: 60,
        createdAt: now,
    }).returning();

    const [module1_3] = await db.insert(courseModules).values({
        courseId: course1.id,
        order: 3,
        title: 'Reduction Strategies',
        description: 'Develop actionable strategies to reduce your carbon footprint.',
        estimatedMinutes: 75,
        createdAt: now,
    }).returning();

    // Insert lessons for Module 1.1
    await db.insert(lessons).values([
        {
            moduleId: module1_1.id,
            order: 1,
            title: 'What is Carbon Footprint?',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. Understanding your carbon footprint is the first step toward reducing your environmental impact and building a sustainable business.'
            }),
            isRequired: true,
            estimatedMinutes: 15,
            createdAt: now,
        },
        {
            moduleId: module1_1.id,
            order: 2,
            title: 'GHG Protocol Overview',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'The Greenhouse Gas Protocol is the most widely used international accounting tool for government and business leaders to understand, quantify, and manage greenhouse gas emissions. This lesson covers the comprehensive framework and its applications.'
            }),
            videoUrl: '/videos/ghg-protocol.mp4',
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module1_1.id,
            order: 3,
            title: 'Module 1 Quiz',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 10,
            createdAt: now,
        }
    ]);

    // Insert lessons for Module 1.2
    await db.insert(lessons).values([
        {
            moduleId: module1_2.id,
            order: 1,
            title: 'Scope 1, 2, and 3 Emissions',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Emissions are categorized into three scopes: Scope 1 (direct emissions from owned sources), Scope 2 (indirect emissions from purchased energy), and Scope 3 (all other indirect emissions in the value chain). Understanding these distinctions is crucial for comprehensive carbon accounting.'
            }),
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module1_2.id,
            order: 2,
            title: 'Identifying Your Emissions',
            contentType: 'exercise',
            contentJson: JSON.stringify({
                exerciseType: 'practical',
                instructions: 'Complete the emissions identification worksheet for your organization. Map out all major emission sources across Scope 1, 2, and 3 categories. This practical exercise will form the foundation of your carbon accounting system.'
            }),
            isRequired: true,
            estimatedMinutes: 30,
            createdAt: now,
        },
        {
            moduleId: module1_2.id,
            order: 3,
            title: 'Module 2 Assessment',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 10,
            createdAt: now,
        }
    ]);

    // Insert lessons for Module 1.3
    await db.insert(lessons).values([
        {
            moduleId: module1_3.id,
            order: 1,
            title: 'Energy Efficiency Best Practices',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Energy efficiency is one of the most cost-effective ways to reduce carbon emissions. This lesson covers proven strategies including equipment upgrades, building automation, behavioral changes, and operational improvements that can significantly reduce your energy consumption and costs.'
            }),
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        },
        {
            moduleId: module1_3.id,
            order: 2,
            title: 'Renewable Energy Options',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'Transitioning to renewable energy is a powerful way to reduce carbon emissions. This video explores various renewable energy options including solar PV, wind power, renewable energy certificates (RECs), and power purchase agreements (PPAs). Learn how to evaluate which options are right for your business.'
            }),
            videoUrl: '/videos/renewable-energy.mp4',
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module1_3.id,
            order: 3,
            title: 'Creating Your Action Plan',
            contentType: 'exercise',
            contentJson: JSON.stringify({
                exerciseType: 'practical',
                instructions: 'Develop a comprehensive carbon reduction action plan for your organization. Prioritize initiatives based on impact, cost, and feasibility. Set specific targets and timelines for implementation. This plan will serve as your roadmap for reducing emissions.'
            }),
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module1_3.id,
            order: 4,
            title: 'Final Assessment',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 10,
            createdAt: now,
        }
    ]);

    // Insert Course 2: Renewable Energy Transition
    const [course2] = await db.insert(courses).values({
        title: 'Renewable Energy Transition',
        description: 'Deep dive into renewable energy technologies, implementation planning, and ROI analysis for businesses ready to transition to clean energy.',
        industry: 'energy',
        difficultyLevel: 'intermediate',
        estimatedHours: 6.0,
        prerequisites: JSON.stringify([1]),
        learningObjectives: JSON.stringify([
            'Evaluate different renewable energy technologies',
            'Conduct feasibility analysis for solar and wind installations',
            'Understand energy storage solutions',
            'Develop implementation roadmaps'
        ]),
        createdBy: 'admin',
        isPublished: true,
        tags: JSON.stringify(['renewable', 'solar', 'wind', 'energy-storage']),
        thumbnailUrl: '/courses/renewable-energy.jpg',
        createdAt: now,
        updatedAt: now,
    }).returning();

    // Insert modules for Course 2
    const [module2_1] = await db.insert(courseModules).values({
        courseId: course2.id,
        order: 1,
        title: 'Solar Power Systems',
        description: 'Comprehensive guide to solar energy technology and implementation.',
        estimatedMinutes: 60,
        createdAt: now,
    }).returning();

    const [module2_2] = await db.insert(courseModules).values({
        courseId: course2.id,
        order: 2,
        title: 'Wind Energy',
        description: 'Understanding wind power systems and commercial applications.',
        estimatedMinutes: 55,
        createdAt: now,
    }).returning();

    const [module2_3] = await db.insert(courseModules).values({
        courseId: course2.id,
        order: 3,
        title: 'Energy Storage Solutions',
        description: 'Explore battery technologies and grid integration strategies.',
        estimatedMinutes: 70,
        createdAt: now,
    }).returning();

    const [module2_4] = await db.insert(courseModules).values({
        courseId: course2.id,
        order: 4,
        title: 'Implementation Planning',
        description: 'Create detailed renewable energy implementation plans with ROI analysis.',
        estimatedMinutes: 75,
        createdAt: now,
    }).returning();

    // Insert lessons for Module 2.1
    await db.insert(lessons).values([
        {
            moduleId: module2_1.id,
            order: 1,
            title: 'Solar Technology Basics',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Solar photovoltaic (PV) technology converts sunlight directly into electricity using semiconductor materials. This lesson covers the fundamentals of solar cells, panels, inverters, and system components. Learn about different types of solar technologies including monocrystalline, polycrystalline, and thin-film panels.'
            }),
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module2_1.id,
            order: 2,
            title: 'Site Assessment & Feasibility',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'Conducting a thorough site assessment is critical for solar project success. This video demonstrates how to evaluate roof conditions, solar irradiance, shading analysis, structural capacity, and electrical infrastructure. Learn to use professional tools and methodologies for accurate feasibility studies.'
            }),
            videoUrl: '/videos/solar-assessment.mp4',
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        },
        {
            moduleId: module2_1.id,
            order: 3,
            title: 'Solar Quiz',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 15,
            createdAt: now,
        }
    ]);

    // Insert lessons for Module 2.2
    await db.insert(lessons).values([
        {
            moduleId: module2_2.id,
            order: 1,
            title: 'Wind Power Fundamentals',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Wind energy harnesses the kinetic energy of moving air to generate electricity. This lesson explores wind turbine technology, site selection criteria, wind resource assessment, and the economics of wind power. Understand the factors that determine wind project viability including wind speed, turbulence, and air density.'
            }),
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module2_2.id,
            order: 2,
            title: 'Commercial Wind Applications',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'Commercial and industrial wind applications offer significant opportunities for businesses with suitable sites. This video showcases real-world case studies of successful wind installations, from small distributed generation to large-scale wind farms. Learn about permitting, interconnection, and operational considerations.'
            }),
            videoUrl: '/videos/wind-power.mp4',
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module2_2.id,
            order: 3,
            title: 'Wind Assessment',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 15,
            createdAt: now,
        }
    ]);

    // Insert lessons for Module 2.3
    await db.insert(lessons).values([
        {
            moduleId: module2_3.id,
            order: 1,
            title: 'Battery Technologies',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Energy storage is essential for maximizing renewable energy value. This lesson covers lithium-ion, flow batteries, and emerging storage technologies. Learn about battery chemistry, capacity, power ratings, cycle life, and safety considerations. Understand how storage systems enable time-shifting, demand charge reduction, and grid services.'
            }),
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        },
        {
            moduleId: module2_3.id,
            order: 2,
            title: 'Grid Integration',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'Integrating renewable energy and storage with the electrical grid requires careful planning and compliance with interconnection standards. This video explains grid services, inverter requirements, protection systems, and utility coordination. Learn about net metering, demand response, and virtual power plants.'
            }),
            videoUrl: '/videos/grid-integration.mp4',
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module2_3.id,
            order: 3,
            title: 'Storage Exercise',
            contentType: 'exercise',
            contentJson: JSON.stringify({
                exerciseType: 'practical',
                instructions: 'Design an energy storage system for a commercial facility. Analyze load profiles, size the battery system, evaluate economic benefits including demand charge savings and energy arbitrage. Calculate payback period and return on investment. This exercise applies real-world engineering and financial analysis.'
            }),
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        }
    ]);

    // Insert lessons for Module 2.4
    await db.insert(lessons).values([
        {
            moduleId: module2_4.id,
            order: 1,
            title: 'ROI Analysis',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Financial analysis is critical for renewable energy project approval. This lesson teaches comprehensive ROI modeling including capital costs, operating expenses, incentives, tax benefits, energy savings, and revenue streams. Learn to calculate NPV, IRR, payback period, and levelized cost of energy (LCOE). Understand financing options including loans, leases, and PPAs.'
            }),
            isRequired: true,
            estimatedMinutes: 30,
            createdAt: now,
        },
        {
            moduleId: module2_4.id,
            order: 2,
            title: 'Project Planning',
            contentType: 'exercise',
            contentJson: JSON.stringify({
                exerciseType: 'practical',
                instructions: 'Create a complete renewable energy project implementation plan. Develop project timeline, identify stakeholders, plan procurement strategy, address permitting requirements, and establish monitoring procedures. Include risk assessment and mitigation strategies. This capstone exercise integrates all course concepts.'
            }),
            isRequired: true,
            estimatedMinutes: 30,
            createdAt: now,
        },
        {
            moduleId: module2_4.id,
            order: 3,
            title: 'Final Exam',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 15,
            createdAt: now,
        }
    ]);

    // Insert Course 3: ESG Reporting for SMEs
    const [course3] = await db.insert(courses).values({
        title: 'ESG Reporting for SMEs',
        description: 'Master ESG frameworks, data collection methodologies, and comprehensive sustainability report preparation for small and medium enterprises.',
        industry: 'finance',
        difficultyLevel: 'advanced',
        estimatedHours: 5.5,
        prerequisites: JSON.stringify([1, 2]),
        learningObjectives: JSON.stringify([
            'Understand major ESG frameworks (GRI, SASB, TCFD)',
            'Design data collection systems',
            'Prepare materiality assessments',
            'Create comprehensive ESG reports'
        ]),
        createdBy: 'admin',
        isPublished: true,
        tags: JSON.stringify(['esg', 'reporting', 'compliance', 'frameworks']),
        thumbnailUrl: '/courses/esg-reporting.jpg',
        createdAt: now,
        updatedAt: now,
    }).returning();

    // Insert modules for Course 3
    const [module3_1] = await db.insert(courseModules).values({
        courseId: course3.id,
        order: 1,
        title: 'ESG Frameworks',
        description: 'Comprehensive overview of major ESG reporting frameworks and standards.',
        estimatedMinutes: 90,
        createdAt: now,
    }).returning();

    const [module3_2] = await db.insert(courseModules).values({
        courseId: course3.id,
        order: 2,
        title: 'Data Collection & Materiality',
        description: 'Learn to design effective data collection systems and conduct materiality assessments.',
        estimatedMinutes: 80,
        createdAt: now,
    }).returning();

    const [module3_3] = await db.insert(courseModules).values({
        courseId: course3.id,
        order: 3,
        title: 'Report Preparation',
        description: 'Master the art of creating comprehensive, stakeholder-ready ESG reports.',
        estimatedMinutes: 100,
        createdAt: now,
    }).returning();

    // Insert lessons for Module 3.1
    await db.insert(lessons).values([
        {
            moduleId: module3_1.id,
            order: 1,
            title: 'Introduction to ESG',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Environmental, Social, and Governance (ESG) reporting has become essential for businesses of all sizes. This lesson introduces the ESG landscape, stakeholder expectations, regulatory trends, and the business case for sustainability reporting. Understand why investors, customers, and regulators increasingly demand ESG transparency and accountability.'
            }),
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        },
        {
            moduleId: module3_1.id,
            order: 2,
            title: 'GRI Standards Overview',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'The Global Reporting Initiative (GRI) Standards are the most widely adopted framework for sustainability reporting worldwide. This video provides a comprehensive walkthrough of the GRI Standards, including universal standards, topic-specific standards, and sector standards. Learn how to apply GRI principles of accuracy, balance, clarity, comparability, completeness, sustainability context, timeliness, and verifiability.'
            }),
            videoUrl: '/videos/gri-standards.mp4',
            isRequired: true,
            estimatedMinutes: 30,
            createdAt: now,
        },
        {
            moduleId: module3_1.id,
            order: 3,
            title: 'SASB and TCFD',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'The Sustainability Accounting Standards Board (SASB) and Task Force on Climate-related Financial Disclosures (TCFD) provide industry-specific and climate-focused reporting frameworks. SASB standards address financially material sustainability topics by industry, while TCFD focuses on climate-related risks and opportunities. Learn when and how to apply these frameworks alongside or instead of GRI.'
            }),
            isRequired: true,
            estimatedMinutes: 20,
            createdAt: now,
        },
        {
            moduleId: module3_1.id,
            order: 4,
            title: 'Framework Quiz',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 15,
            createdAt: now,
        }
    ]);

    // Insert lessons for Module 3.2
    await db.insert(lessons).values([
        {
            moduleId: module3_2.id,
            order: 1,
            title: 'Materiality Assessment Process',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'Materiality assessment is the foundation of effective ESG reporting. This lesson teaches how to identify, evaluate, and prioritize ESG topics based on their significance to stakeholders and business impact. Learn the double materiality concept that considers both financial materiality (impact on business) and impact materiality (impact on society and environment). Master stakeholder engagement techniques and materiality matrices.'
            }),
            isRequired: true,
            estimatedMinutes: 30,
            createdAt: now,
        },
        {
            moduleId: module3_2.id,
            order: 2,
            title: 'Setting Up Data Collection',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'Reliable ESG data is essential for credible reporting. This video demonstrates how to design and implement data collection systems for ESG metrics across environmental, social, and governance dimensions. Learn about data sources, collection frequency, validation procedures, and data management systems. Understand how to engage internal stakeholders and establish accountability for data quality.'
            }),
            videoUrl: '/videos/data-collection.mp4',
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        },
        {
            moduleId: module3_2.id,
            order: 3,
            title: 'Stakeholder Engagement',
            contentType: 'exercise',
            contentJson: JSON.stringify({
                exerciseType: 'practical',
                instructions: 'Develop a stakeholder engagement plan for your ESG reporting process. Identify key stakeholder groups, design engagement methods (surveys, interviews, workshops), create materiality survey questions, and plan how to incorporate stakeholder input into your materiality assessment. This exercise will guide your actual stakeholder engagement efforts.'
            }),
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        }
    ]);

    // Insert lessons for Module 3.3
    await db.insert(lessons).values([
        {
            moduleId: module3_3.id,
            order: 1,
            title: 'Report Structure',
            contentType: 'text',
            contentJson: JSON.stringify({
                text: 'An effective ESG report tells a compelling story while providing comprehensive data disclosure. This lesson covers report structure best practices including executive summary, company profile, governance and strategy, materiality process, performance data, targets and commitments, and stakeholder engagement. Learn how to balance narrative storytelling with quantitative disclosure and create reports that resonate with different audiences.'
            }),
            isRequired: true,
            estimatedMinutes: 30,
            createdAt: now,
        },
        {
            moduleId: module3_3.id,
            order: 2,
            title: 'Data Visualization Best Practices',
            contentType: 'video',
            contentJson: JSON.stringify({
                transcript: 'Effective data visualization makes ESG reports more accessible and impactful. This video teaches design principles for charts, graphs, infographics, and dashboards that communicate ESG performance clearly and compellingly. Learn when to use different visualization types, how to highlight trends and progress, and how to maintain consistency with brand guidelines while ensuring accessibility.'
            }),
            videoUrl: '/videos/data-viz.mp4',
            isRequired: true,
            estimatedMinutes: 25,
            createdAt: now,
        },
        {
            moduleId: module3_3.id,
            order: 3,
            title: 'Writing Your Report',
            contentType: 'exercise',
            contentJson: JSON.stringify({
                exerciseType: 'practical',
                instructions: 'Create the outline and draft key sections of your organization\'s ESG report. Apply the frameworks learned in this course, incorporate your materiality assessment results, and present your ESG data using effective storytelling and visualization techniques. Include governance disclosure, performance data, targets, and stakeholder engagement results. This capstone exercise produces a draft report framework you can build upon.'
            }),
            isRequired: true,
            estimatedMinutes: 30,
            createdAt: now,
        },
        {
            moduleId: module3_3.id,
            order: 4,
            title: 'Final ESG Assessment',
            contentType: 'quiz',
            contentJson: JSON.stringify({
                questionCount: 5,
                type: 'multiple-choice'
            }),
            isRequired: true,
            estimatedMinutes: 15,
            createdAt: now,
        }
    ]);

    console.log('✅ Courses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});