-- Additive storage for the grant-alerts scheduled scan. The Worker accesses
-- this only through the Supabase service-role HTTP client.
create table if not exists public.grant_opportunities (
  id bigint generated by default as identity primary key,
  source text not null,
  external_id text not null,
  title text not null,
  summary text not null default '',
  url text not null,
  program text,
  deadline text,
  published_at text,
  score real not null default 0,
  reasons text not null default '',
  first_seen_at timestamptz not null default now(),
  notified_at timestamptz,
  unique (source, external_id)
);

create index if not exists grant_opps_first_seen_idx
  on public.grant_opportunities (first_seen_at desc);

create table if not exists public.grant_alert_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  sources text not null default 'eu-funding-tenders,research-gov-cy,invest-cyprus,kebe-oeb,accelerators',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.grant_opportunities enable row level security;
alter table public.grant_alert_subscriptions enable row level security;
revoke all on table public.grant_opportunities from anon, authenticated;
revoke all on table public.grant_alert_subscriptions from anon, authenticated;
