/**
 * Official EU CBAM reference data for the definitive period. Pure lookups,
 * no I/O. Every value comes from a dated legal text; nothing is estimated here.
 *
 * - Default values: Implementing Regulation (EU) 2025/2621, Annexes I and IV as
 *   replaced by Implementing Regulation (EU) 2026/1740 (applies from 1 Jan 2026).
 * - CBAM benchmarks: Implementing Regulation (EU) 2025/2620, Annex point 5.
 * - Cross-sectoral correction factor 2026-2030: Implementing Decision (EU) 2026/1862 (100 %).
 * - CBAM factor: Article 10a(1a) of Directive 2003/87/EC.
 * - Certificate prices: published quarterly by DG TAXUD (Implementing Regulation (EU) 2025/2548).
 *
 * The JSON files are generated by scripts/cbam/*.py from the EUR-Lex pages.
 * Electricity factors (Annexes II and III) are IEA data under a non-commercial
 * licence and are deliberately not shipped.
 */

import defaults from "@/data/cbam/default-values-2026.json";
import benchmarks from "@/data/cbam/benchmarks-2026.json";

export type CbamSector = "cement" | "iron-steel" | "aluminium" | "fertilisers" | "hydrogen" | "electricity";

type Row = [number | null, number | null, number, string | null];
type BmEntry = [number, string | null, number | null];

const D = defaults as unknown as {
  source: { regulation: string; url: string; appliesFrom: string; publishedOJ: string };
  markups: { default: Record<string, number>; fertilisers: Record<string, number> };
  routes: Record<string, string>;
  other: Record<string, Row>;
  annexIV: Record<string, Row>;
  goods: Record<string, string>;
  countries: Record<string, { name: string; rows: Record<string, Row> }>;
};
const B = benchmarks as unknown as { source: { regulation: string; url: string }; benchmarks: Record<string, { a: BmEntry[]; b: BmEntry[] }> };

export const DEFAULTS_SOURCE = D.source;
export const BENCHMARKS_SOURCE = B.source;
export const ROUTES = D.routes;

export const digits = (code: string) => code.replace(/\D/g, "");

/** Sector of a CN code, from the chapter headings in Annex I of Regulation (EU) 2023/956. */
export function sectorOf(code: string): CbamSector | null {
  const d = digits(code);
  if (d.startsWith("2716")) return "electricity";
  if (d.startsWith("280410")) return "hydrogen";
  if (d.startsWith("2507") || d.startsWith("2523")) return "cement";
  if (["2808", "2814", "283421", "3102", "3105"].some((p) => d.startsWith(p))) return "fertilisers";
  if (d.startsWith("260112") || d.startsWith("72") || d.startsWith("73")) return "iron-steel";
  if (d.startsWith("76")) return "aluminium";
  return null;
}

/** Keys of a table that fit a declared code: the table heading the code falls under, or the codes under a short declared code. */
function matchKeys(table: Record<string, unknown>, d: string): { keys: string[]; exact: boolean } {
  let best = "";
  for (const k of Object.keys(table)) if (d.startsWith(k) && k.length > best.length) best = k;
  if (best) return { keys: [best], exact: true };
  const wider = Object.keys(table).filter((k) => k.startsWith(d));
  return { keys: wider, exact: wider.length === 1 };
}

export interface GoodInfo {
  code: string;
  description: string;
  sector: CbamSector;
  /** True when the declared code points at exactly one official entry. */
  exact: boolean;
}

/** The official CBAM good for a declared CN code, or null when it is not a CBAM good. */
export function lookupGood(code: string): GoodInfo | null {
  const d = digits(code);
  if (d.length < 4) return null;
  if (d.startsWith("2716")) return { code: "27160000", description: "Electrical energy", sector: "electricity", exact: true };
  const { keys, exact } = matchKeys(D.goods, d);
  if (!keys.length) return null;
  const sector = sectorOf(keys[0]);
  if (!sector) return null;
  return { code: keys.length === 1 ? keys[0] : d, description: keys.length === 1 ? D.goods[keys[0]] : `${keys.length} CBAM goods under ${d}`, sector, exact };
}

export interface DefaultValue {
  /** tCO2e per tonne. Direct and indirect are given for information only. */
  direct: number | null;
  indirect: number | null;
  total: number;
  route: string | null;
  table: "country" | "other" | "unknown_origin";
  /** Name of the country table used, or the fallback table. */
  tableName: string;
  /** False when a short CN code matched several entries and the highest was taken. */
  exact: boolean;
}

function pick(table: Record<string, Row>, d: string): { row: Row; exact: boolean } | null {
  const { keys, exact } = matchKeys(table, d);
  if (!keys.length) return null;
  // Several codes fit a short declared code: take the highest total, never the lowest.
  const row = keys.map((k) => table[k]).sort((a, b) => b[2] - a[2])[0];
  return { row, exact };
}

/**
 * The official default value for a good from a country of origin. Falls back
 * to "Other countries and territories" when the country has no value, and to
 * Annex IV (highest value) when the origin is unknown.
 */
export function lookupDefault(code: string, originIso2: string | null): DefaultValue | null {
  const d = digits(code);
  if (d.length < 4 || d.startsWith("2716")) return null;
  const iso = (originIso2 ?? "").trim().toUpperCase();
  if (!iso || iso === "OTHER" || iso === "XX") {
    const hit = pick(D.annexIV, d);
    return hit ? { direct: null, indirect: null, total: hit.row[2], route: hit.row[3], table: "unknown_origin", tableName: "Annex IV (origin unknown)", exact: hit.exact } : null;
  }
  const country = D.countries[iso];
  const own = country ? pick(country.rows, d) : null;
  if (own) return { direct: own.row[0], indirect: own.row[1], total: own.row[2], route: own.row[3], table: "country", tableName: country!.name, exact: own.exact };
  const other = pick(D.other, d);
  return other
    ? { direct: other.row[0], indirect: other.row[1], total: other.row[2], route: other.row[3], table: "other", tableName: "Other countries and territories", exact: other.exact }
    : null;
}

/** Mark-up added to default values when working out certificates (Annex I intro). */
export function markupFor(year: number, sector: CbamSector): number {
  const table = sector === "fertilisers" ? D.markups.fertilisers : D.markups.default;
  const years = Object.keys(table).map(Number).filter((y) => y <= year).sort((a, b) => b - a);
  return years.length ? table[String(years[0])] : 0;
}

/** Share of EU free allocation still given, Article 10a(1a) Directive 2003/87/EC. */
const CBAM_FACTOR: Record<number, number> = {
  2026: 0.975, 2027: 0.95, 2028: 0.9, 2029: 0.775, 2030: 0.515, 2031: 0.39, 2032: 0.265, 2033: 0.14,
};
export function cbamFactor(year: number): number {
  if (year < 2026) return 1;
  return CBAM_FACTOR[year] ?? 0;
}

/** Cross-sectoral correction factor, Implementing Decision (EU) 2026/1862. Unknown after 2030. */
export function cscf(year: number): number | null {
  return year >= 2026 && year <= 2030 ? 1 : null;
}

export interface Benchmark {
  value: number;
  /** False when the code or route was ambiguous and the lowest benchmark was used (higher cost). */
  exact: boolean;
}

/**
 * CBAM benchmark for a good. Column B goes with default values, column A with
 * actual data (for complex goods column A leaves out precursors, so the cost
 * is an upper estimate).
 */
export function lookupBenchmark(code: string, year: number, route: string | null, column: "a" | "b"): Benchmark | null {
  const d = digits(code);
  const { keys, exact: codeExact } = matchKeys(B.benchmarks, d);
  if (!keys.length) return null;
  const period = year <= 2027 ? 1 : 2;
  let exact = codeExact;
  const perCode = keys.map((k) => {
    const all = B.benchmarks[k][column];
    const inPeriod = all.filter((e) => e[2] === null || e[2] === period);
    const routed = route ? inPeriod.filter((e) => e[1] === route) : [];
    const pool = routed.length ? routed : inPeriod;
    if (!routed.length && new Set(pool.map((e) => e[0])).size > 1) {
      // 5.1: several alloy grades for one code -> the highest benchmark applies.
      if (!route || !pool.some((e) => e[1])) return Math.max(...pool.map((e) => e[0]));
      exact = false;
    }
    return Math.max(...pool.map((e) => e[0]));
  });
  if (perCode.length > 1) exact = false;
  // Several codes fit: the lowest benchmark gives the highest cost, never an understatement.
  return { value: Math.min(...perCode), exact };
}

/** Official quarterly CBAM certificate prices for 2026, EUR per certificate (1 tCO2e). */
export const CERTIFICATE_PRICES: Record<string, { eur: number; published: string }> = {
  "2026-Q1": { eur: 75.36, published: "2026-04-07" },
  "2026-Q2": { eur: 75.28, published: "2026-07-06" },
};
export const CERTIFICATE_PRICE_SOURCE = "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/price-cbam-certificates_en";

export interface PriceUse {
  eur: number;
  quarter: string;
  /** True when the quarter has no published price yet and the latest published one stands in. */
  provisional: boolean;
  basisQuarter: string;
}

export function certificatePrice(importDate: string): PriceUse | null {
  const y = Number(importDate.slice(0, 4));
  const m = Number(importDate.slice(5, 7));
  if (!y || !m) return null;
  const quarter = `${y}-Q${Math.ceil(m / 3)}`;
  const own = CERTIFICATE_PRICES[quarter];
  if (own) return { eur: own.eur, quarter, provisional: false, basisQuarter: quarter };
  const latest = Object.keys(CERTIFICATE_PRICES).sort().pop();
  if (!latest) return null;
  return { eur: CERTIFICATE_PRICES[latest].eur, quarter, provisional: true, basisQuarter: latest };
}
